/* Generated by tools/shaders.py from shaders/ui.glsl; do not edit.
 * Regenerate with `python3 tools/shaders.py generate`; `check` verifies the hash below.
 * Compiler: shaderc v2023.8 unknown hash, 2025-09-26, target vulkan1.3.
 *
 * Every dialect of the draw list's one shader. It existed three times by hand until F133,
 * and those copies disagreed about their own attribute numbering and their Y convention. */
#ifndef RENGINE_UI_SHADERS_H
#define RENGINE_UI_SHADERS_H
#include <stdint.h>

#define RE_UI_SHADER_SOURCE_SHA256 "ea5d8a4fe2dbda7ea3b3a3f045e280ab0a91c43e99dd55ee5a45e3dd715af925"

static const char re_ui_vertex_glsl[] =
  "#version 330 core\n"
  "#define IN(loc) layout(location = loc) in\n"
  "#define OUT(loc) out\n"
  "#define FLAT_OUT(loc) flat out\n"
  "#define IN_F(loc) in\n"
  "#define FLAT_IN(loc) flat in\n"
  "#define OUT_COLOR out vec4 o_color;\n"
  "#define VERTEX 1\n"
  "// The draw list's one shader, in one source (spec 124, F133).\n"
  "//\n"
  "// It used to exist three times: inline GLSL in backend_gl.c, this directory's ui.vert/ui.frag for\n"
  "// the Vulkan adapter, and inline MSL in backend_metal.m. The signed-distance maths agreed, because\n"
  "// someone kept it agreeing; the INTERFACES did not — the Vulkan copy numbered its attributes\n"
  "// shape, radii, pos, uv, extra, color while the OpenGL copy numbered them pos, uv, color, shape,\n"
  "// radii, extra, and the two emitted opposite Y. Three dialects of one shader is a drift risk; three\n"
  "// dialects that already disagreed about their own vertex layout is the drift.\n"
  "//\n"
  "// One layout now, and one Y. The seam's backends store NDC -1 in row 0 on every API (see the long\n"
  "// note in gpu_seam_vk.c), so the OpenGL formula is the formula everywhere: logical y counts down\n"
  "// from the top of the window, and 1.0 - y/h*2 puts it where every backend agrees it goes.\n"
  "//\n"
  "// Modes: 0 solid, 1 rounded fill, 2 ring, 3 shadow, 4 coverage atlas, 5 RGBA texture.\n"
  "\n"
  "uniform vec4 u_size;\n"
  "uniform sampler2D u_texture;\n"
  "\n"
  "#ifdef VERTEX\n"
  "IN(0) vec2 a_pos;\n"
  "IN(1) vec2 a_uv;\n"
  "IN(2) vec4 a_color;\n"
  "IN(3) vec4 a_shape;\n"
  "IN(4) vec4 a_radii;\n"
  "IN(5) vec2 a_extra;\n"
  "OUT(0) vec2 v_pos;\n"
  "OUT(1) vec2 v_uv;\n"
  "OUT(2) vec4 v_color;\n"
  "FLAT_OUT(3) vec4 v_shape;\n"
  "FLAT_OUT(4) vec4 v_radii;\n"
  "FLAT_OUT(5) vec2 v_extra;\n"
  "void main() {\n"
  "  v_pos = a_pos; v_uv = a_uv; v_color = a_color;\n"
  "  v_shape = a_shape; v_radii = a_radii; v_extra = a_extra;\n"
  "  gl_Position = vec4(a_pos.x / u_size.x * 2.0 - 1.0, 1.0 - a_pos.y / u_size.y * 2.0, 0.0, 1.0);\n"
  "}\n"
  "#else\n"
  "IN_F(0) vec2 v_pos;\n"
  "IN_F(1) vec2 v_uv;\n"
  "IN_F(2) vec4 v_color;\n"
  "FLAT_IN(3) vec4 v_shape;\n"
  "FLAT_IN(4) vec4 v_radii;\n"
  "FLAT_IN(5) vec2 v_extra;\n"
  "OUT_COLOR\n"
  "float box(vec2 p, vec2 h, float r) { vec2 q = abs(p) - (h - vec2(r)); return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - r; }\n"
  "float corner(vec2 p) { return p.x < 0.0 ? (p.y < 0.0 ? v_radii.x : v_radii.w) : (p.y < 0.0 ? v_radii.y : v_radii.z); }\n"
  "void main() {\n"
  "  int mode = int(v_extra.y + 0.5); vec4 c = v_color; vec2 p = v_pos - v_shape.xy; vec2 h = v_shape.zw; float w = v_extra.x;\n"
  "  if (mode == 1) { c.a *= clamp(0.5 - box(p, h, corner(p)), 0.0, 1.0); }\n"
  "  else if (mode == 2) { float r = corner(p); float o = clamp(0.5 - box(p, h, r), 0.0, 1.0);\n"
  "    float i = clamp(0.5 - box(p, h - vec2(w), max(r - w, 0.0)), 0.0, 1.0); c.a *= o * (1.0 - i); }\n"
  "  else if (mode == 3) { c.a *= 1.0 - smoothstep(0.0, w, box(p, h, corner(p))); }\n"
  "  else if (mode == 4) { c.a *= texture(u_texture, v_uv).r; }\n"
  "  else if (mode == 5) { c *= texture(u_texture, v_uv); }\n"
  "  if (c.a <= 0.0) discard;\n"
  "  o_color = c;\n"
  "}\n"
  "#endif\n";
static const char re_ui_vertex_msl[] =
  "#include <metal_stdlib>\n"
  "#include <simd/simd.h>\n"
  "\n"
  "using namespace metal;\n"
  "\n"
  "struct Uniforms\n"
  "{\n"
  "    float4 u_size;\n"
  "};\n"
  "\n"
  "struct main0_out\n"
  "{\n"
  "    float2 v_pos [[user(locn0)]];\n"
  "    float2 v_uv [[user(locn1)]];\n"
  "    float4 v_color [[user(locn2)]];\n"
  "    float4 v_shape [[user(locn3)]];\n"
  "    float4 v_radii [[user(locn4)]];\n"
  "    float2 v_extra [[user(locn5)]];\n"
  "    float4 gl_Position [[position]];\n"
  "};\n"
  "\n"
  "struct main0_in\n"
  "{\n"
  "    float2 a_pos [[attribute(0)]];\n"
  "    float2 a_uv [[attribute(1)]];\n"
  "    float4 a_color [[attribute(2)]];\n"
  "    float4 a_shape [[attribute(3)]];\n"
  "    float4 a_radii [[attribute(4)]];\n"
  "    float2 a_extra [[attribute(5)]];\n"
  "};\n"
  "\n"
  "vertex main0_out main0(main0_in in [[stage_in]], constant Uniforms& _45 [[buffer(0)]])\n"
  "{\n"
  "    main0_out out = {};\n"
  "    out.v_pos = in.a_pos;\n"
  "    out.v_uv = in.a_uv;\n"
  "    out.v_color = in.a_color;\n"
  "    out.v_shape = in.a_shape;\n"
  "    out.v_radii = in.a_radii;\n"
  "    out.v_extra = in.a_extra;\n"
  "    out.gl_Position = float4(((in.a_pos.x / _45.u_size.x) * 2.0) - 1.0, 1.0 - ((in.a_pos.y / _45.u_size.y) * 2.0), 0.0, 1.0);\n"
  "    out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal\n"
  "    return out;\n"
  "}\n"
  "\n";
static const uint32_t re_ui_vertex_spv[] = {
  0x07230203u, 0x00010600u, 0x000d000bu, 0x00000040u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
  0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
  0x0013000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00000009u, 0x0000000bu, 0x0000000du,
  0x0000000eu, 0x00000012u, 0x00000014u, 0x00000016u, 0x00000017u, 0x00000019u, 0x0000001au, 0x0000001cu,
  0x0000001du, 0x00000024u, 0x0000002du, 0x00030003u, 0x00000002u, 0x000001c2u, 0x000a0004u, 0x475f4c47u,
  0x4c474f4fu, 0x70635f45u, 0x74735f70u, 0x5f656c79u, 0x656e696cu, 0x7269645fu, 0x69746365u, 0x00006576u,
  0x00080004u, 0x475f4c47u, 0x4c474f4fu, 0x6e695f45u, 0x64756c63u, 0x69645f65u, 0x74636572u, 0x00657669u,
  0x00040005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00040005u, 0x00000009u, 0x6f705f76u, 0x00000073u,
  0x00040005u, 0x0000000bu, 0x6f705f61u, 0x00000073u, 0x00040005u, 0x0000000du, 0x76755f76u, 0x00000000u,
  0x00040005u, 0x0000000eu, 0x76755f61u, 0x00000000u, 0x00040005u, 0x00000012u, 0x6f635f76u, 0x00726f6cu,
  0x00040005u, 0x00000014u, 0x6f635f61u, 0x00726f6cu, 0x00040005u, 0x00000016u, 0x68735f76u, 0x00657061u,
  0x00040005u, 0x00000017u, 0x68735f61u, 0x00657061u, 0x00040005u, 0x00000019u, 0x61725f76u, 0x00696964u,
  0x00040005u, 0x0000001au, 0x61725f61u, 0x00696964u, 0x00040005u, 0x0000001cu, 0x78655f76u, 0x00617274u,
  0x00040005u, 0x0000001du, 0x78655f61u, 0x00617274u, 0x00060005u, 0x00000022u, 0x505f6c67u, 0x65567265u,
  0x78657472u, 0x00000000u, 0x00060006u, 0x00000022u, 0x00000000u, 0x505f6c67u, 0x7469736fu, 0x006e6f69u,
  0x00070006u, 0x00000022u, 0x00000001u, 0x505f6c67u, 0x746e696fu, 0x657a6953u, 0x00000000u, 0x00070006u,
  0x00000022u, 0x00000002u, 0x435f6c67u, 0x4470696cu, 0x61747369u, 0x0065636eu, 0x00070006u, 0x00000022u,
  0x00000003u, 0x435f6c67u, 0x446c6c75u, 0x61747369u, 0x0065636eu, 0x00030005u, 0x00000024u, 0x00000000u,
  0x00050005u, 0x0000002bu, 0x66696e55u, 0x736d726fu, 0x00000000u, 0x00050006u, 0x0000002bu, 0x00000000u,
  0x69735f75u, 0x0000657au, 0x00030005u, 0x0000002du, 0x00000000u, 0x00040047u, 0x00000009u, 0x0000001eu,
  0x00000000u, 0x00040047u, 0x0000000bu, 0x0000001eu, 0x00000000u, 0x00040047u, 0x0000000du, 0x0000001eu,
  0x00000001u, 0x00040047u, 0x0000000eu, 0x0000001eu, 0x00000001u, 0x00040047u, 0x00000012u, 0x0000001eu,
  0x00000002u, 0x00040047u, 0x00000014u, 0x0000001eu, 0x00000002u, 0x00030047u, 0x00000016u, 0x0000000eu,
  0x00040047u, 0x00000016u, 0x0000001eu, 0x00000003u, 0x00040047u, 0x00000017u, 0x0000001eu, 0x00000003u,
  0x00030047u, 0x00000019u, 0x0000000eu, 0x00040047u, 0x00000019u, 0x0000001eu, 0x00000004u, 0x00040047u,
  0x0000001au, 0x0000001eu, 0x00000004u, 0x00030047u, 0x0000001cu, 0x0000000eu, 0x00040047u, 0x0000001cu,
  0x0000001eu, 0x00000005u, 0x00040047u, 0x0000001du, 0x0000001eu, 0x00000005u, 0x00030047u, 0x00000022u,
  0x00000002u, 0x00050048u, 0x00000022u, 0x00000000u, 0x0000000bu, 0x00000000u, 0x00050048u, 0x00000022u,
  0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u, 0x00000022u, 0x00000002u, 0x0000000bu, 0x00000003u,
  0x00050048u, 0x00000022u, 0x00000003u, 0x0000000bu, 0x00000004u, 0x00030047u, 0x0000002bu, 0x00000002u,
  0x00050048u, 0x0000002bu, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x0000002du, 0x00000021u,
  0x00000000u, 0x00040047u, 0x0000002du, 0x00000022u, 0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u,
  0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u,
  0x00000002u, 0x00040020u, 0x00000008u, 0x00000003u, 0x00000007u, 0x0004003bu, 0x00000008u, 0x00000009u,
  0x00000003u, 0x00040020u, 0x0000000au, 0x00000001u, 0x00000007u, 0x0004003bu, 0x0000000au, 0x0000000bu,
  0x00000001u, 0x0004003bu, 0x00000008u, 0x0000000du, 0x00000003u, 0x0004003bu, 0x0000000au, 0x0000000eu,
  0x00000001u, 0x00040017u, 0x00000010u, 0x00000006u, 0x00000004u, 0x00040020u, 0x00000011u, 0x00000003u,
  0x00000010u, 0x0004003bu, 0x00000011u, 0x00000012u, 0x00000003u, 0x00040020u, 0x00000013u, 0x00000001u,
  0x00000010u, 0x0004003bu, 0x00000013u, 0x00000014u, 0x00000001u, 0x0004003bu, 0x00000011u, 0x00000016u,
  0x00000003u, 0x0004003bu, 0x00000013u, 0x00000017u, 0x00000001u, 0x0004003bu, 0x00000011u, 0x00000019u,
  0x00000003u, 0x0004003bu, 0x00000013u, 0x0000001au, 0x00000001u, 0x0004003bu, 0x00000008u, 0x0000001cu,
  0x00000003u, 0x0004003bu, 0x0000000au, 0x0000001du, 0x00000001u, 0x00040015u, 0x0000001fu, 0x00000020u,
  0x00000000u, 0x0004002bu, 0x0000001fu, 0x00000020u, 0x00000001u, 0x0004001cu, 0x00000021u, 0x00000006u,
  0x00000020u, 0x0006001eu, 0x00000022u, 0x00000010u, 0x00000006u, 0x00000021u, 0x00000021u, 0x00040020u,
  0x00000023u, 0x00000003u, 0x00000022u, 0x0004003bu, 0x00000023u, 0x00000024u, 0x00000003u, 0x00040015u,
  0x00000025u, 0x00000020u, 0x00000001u, 0x0004002bu, 0x00000025u, 0x00000026u, 0x00000000u, 0x0004002bu,
  0x0000001fu, 0x00000027u, 0x00000000u, 0x00040020u, 0x00000028u, 0x00000001u, 0x00000006u, 0x0003001eu,
  0x0000002bu, 0x00000010u, 0x00040020u, 0x0000002cu, 0x00000002u, 0x0000002bu, 0x0004003bu, 0x0000002cu,
  0x0000002du, 0x00000002u, 0x00040020u, 0x0000002eu, 0x00000002u, 0x00000006u, 0x0004002bu, 0x00000006u,
  0x00000032u, 0x40000000u, 0x0004002bu, 0x00000006u, 0x00000034u, 0x3f800000u, 0x0004002bu, 0x00000006u,
  0x0000003du, 0x00000000u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u,
  0x00000005u, 0x0004003du, 0x00000007u, 0x0000000cu, 0x0000000bu, 0x0003003eu, 0x00000009u, 0x0000000cu,
  0x0004003du, 0x00000007u, 0x0000000fu, 0x0000000eu, 0x0003003eu, 0x0000000du, 0x0000000fu, 0x0004003du,
  0x00000010u, 0x00000015u, 0x00000014u, 0x0003003eu, 0x00000012u, 0x00000015u, 0x0004003du, 0x00000010u,
  0x00000018u, 0x00000017u, 0x0003003eu, 0x00000016u, 0x00000018u, 0x0004003du, 0x00000010u, 0x0000001bu,
  0x0000001au, 0x0003003eu, 0x00000019u, 0x0000001bu, 0x0004003du, 0x00000007u, 0x0000001eu, 0x0000001du,
  0x0003003eu, 0x0000001cu, 0x0000001eu, 0x00050041u, 0x00000028u, 0x00000029u, 0x0000000bu, 0x00000027u,
  0x0004003du, 0x00000006u, 0x0000002au, 0x00000029u, 0x00060041u, 0x0000002eu, 0x0000002fu, 0x0000002du,
  0x00000026u, 0x00000027u, 0x0004003du, 0x00000006u, 0x00000030u, 0x0000002fu, 0x00050088u, 0x00000006u,
  0x00000031u, 0x0000002au, 0x00000030u, 0x00050085u, 0x00000006u, 0x00000033u, 0x00000031u, 0x00000032u,
  0x00050083u, 0x00000006u, 0x00000035u, 0x00000033u, 0x00000034u, 0x00050041u, 0x00000028u, 0x00000036u,
  0x0000000bu, 0x00000020u, 0x0004003du, 0x00000006u, 0x00000037u, 0x00000036u, 0x00060041u, 0x0000002eu,
  0x00000038u, 0x0000002du, 0x00000026u, 0x00000020u, 0x0004003du, 0x00000006u, 0x00000039u, 0x00000038u,
  0x00050088u, 0x00000006u, 0x0000003au, 0x00000037u, 0x00000039u, 0x00050085u, 0x00000006u, 0x0000003bu,
  0x0000003au, 0x00000032u, 0x00050083u, 0x00000006u, 0x0000003cu, 0x00000034u, 0x0000003bu, 0x00070050u,
  0x00000010u, 0x0000003eu, 0x00000035u, 0x0000003cu, 0x0000003du, 0x00000034u, 0x00050041u, 0x00000011u,
  0x0000003fu, 0x00000024u, 0x00000026u, 0x0003003eu, 0x0000003fu, 0x0000003eu, 0x000100fdu, 0x00010038u,
};

static const char re_ui_fragment_glsl[] =
  "#version 330 core\n"
  "#define IN(loc) layout(location = loc) in\n"
  "#define OUT(loc) out\n"
  "#define FLAT_OUT(loc) flat out\n"
  "#define IN_F(loc) in\n"
  "#define FLAT_IN(loc) flat in\n"
  "#define OUT_COLOR out vec4 o_color;\n"
  "// The draw list's one shader, in one source (spec 124, F133).\n"
  "//\n"
  "// It used to exist three times: inline GLSL in backend_gl.c, this directory's ui.vert/ui.frag for\n"
  "// the Vulkan adapter, and inline MSL in backend_metal.m. The signed-distance maths agreed, because\n"
  "// someone kept it agreeing; the INTERFACES did not — the Vulkan copy numbered its attributes\n"
  "// shape, radii, pos, uv, extra, color while the OpenGL copy numbered them pos, uv, color, shape,\n"
  "// radii, extra, and the two emitted opposite Y. Three dialects of one shader is a drift risk; three\n"
  "// dialects that already disagreed about their own vertex layout is the drift.\n"
  "//\n"
  "// One layout now, and one Y. The seam's backends store NDC -1 in row 0 on every API (see the long\n"
  "// note in gpu_seam_vk.c), so the OpenGL formula is the formula everywhere: logical y counts down\n"
  "// from the top of the window, and 1.0 - y/h*2 puts it where every backend agrees it goes.\n"
  "//\n"
  "// Modes: 0 solid, 1 rounded fill, 2 ring, 3 shadow, 4 coverage atlas, 5 RGBA texture.\n"
  "\n"
  "uniform vec4 u_size;\n"
  "uniform sampler2D u_texture;\n"
  "\n"
  "#ifdef VERTEX\n"
  "IN(0) vec2 a_pos;\n"
  "IN(1) vec2 a_uv;\n"
  "IN(2) vec4 a_color;\n"
  "IN(3) vec4 a_shape;\n"
  "IN(4) vec4 a_radii;\n"
  "IN(5) vec2 a_extra;\n"
  "OUT(0) vec2 v_pos;\n"
  "OUT(1) vec2 v_uv;\n"
  "OUT(2) vec4 v_color;\n"
  "FLAT_OUT(3) vec4 v_shape;\n"
  "FLAT_OUT(4) vec4 v_radii;\n"
  "FLAT_OUT(5) vec2 v_extra;\n"
  "void main() {\n"
  "  v_pos = a_pos; v_uv = a_uv; v_color = a_color;\n"
  "  v_shape = a_shape; v_radii = a_radii; v_extra = a_extra;\n"
  "  gl_Position = vec4(a_pos.x / u_size.x * 2.0 - 1.0, 1.0 - a_pos.y / u_size.y * 2.0, 0.0, 1.0);\n"
  "}\n"
  "#else\n"
  "IN_F(0) vec2 v_pos;\n"
  "IN_F(1) vec2 v_uv;\n"
  "IN_F(2) vec4 v_color;\n"
  "FLAT_IN(3) vec4 v_shape;\n"
  "FLAT_IN(4) vec4 v_radii;\n"
  "FLAT_IN(5) vec2 v_extra;\n"
  "OUT_COLOR\n"
  "float box(vec2 p, vec2 h, float r) { vec2 q = abs(p) - (h - vec2(r)); return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - r; }\n"
  "float corner(vec2 p) { return p.x < 0.0 ? (p.y < 0.0 ? v_radii.x : v_radii.w) : (p.y < 0.0 ? v_radii.y : v_radii.z); }\n"
  "void main() {\n"
  "  int mode = int(v_extra.y + 0.5); vec4 c = v_color; vec2 p = v_pos - v_shape.xy; vec2 h = v_shape.zw; float w = v_extra.x;\n"
  "  if (mode == 1) { c.a *= clamp(0.5 - box(p, h, corner(p)), 0.0, 1.0); }\n"
  "  else if (mode == 2) { float r = corner(p); float o = clamp(0.5 - box(p, h, r), 0.0, 1.0);\n"
  "    float i = clamp(0.5 - box(p, h - vec2(w), max(r - w, 0.0)), 0.0, 1.0); c.a *= o * (1.0 - i); }\n"
  "  else if (mode == 3) { c.a *= 1.0 - smoothstep(0.0, w, box(p, h, corner(p))); }\n"
  "  else if (mode == 4) { c.a *= texture(u_texture, v_uv).r; }\n"
  "  else if (mode == 5) { c *= texture(u_texture, v_uv); }\n"
  "  if (c.a <= 0.0) discard;\n"
  "  o_color = c;\n"
  "}\n"
  "#endif\n";
static const char re_ui_fragment_msl[] =
  "#include <metal_stdlib>\n"
  "#include <simd/simd.h>\n"
  "\n"
  "using namespace metal;\n"
  "\n"
  "struct main0_out\n"
  "{\n"
  "    float4 o_color [[color(0)]];\n"
  "};\n"
  "\n"
  "struct main0_in\n"
  "{\n"
  "    float2 v_pos [[user(locn0)]];\n"
  "    float2 v_uv [[user(locn1)]];\n"
  "    float4 v_color [[user(locn2)]];\n"
  "    float4 v_shape [[user(locn3), flat]];\n"
  "    float4 v_radii [[user(locn4), flat]];\n"
  "    float2 v_extra [[user(locn5), flat]];\n"
  "};\n"
  "\n"
  "fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> u_texture [[texture(0)]], sampler u_textureSmplr [[sampler(0)]])\n"
  "{\n"
  "    main0_out out = {};\n"
  "    int _97 = int(in.v_extra.y + 0.5);\n"
  "    float4 _101 = in.v_color;\n"
  "    float2 _108 = in.v_pos - in.v_shape.xy;\n"
  "    float4 _485;\n"
  "    if (_97 == 1)\n"
  "    {\n"
  "        float _481;\n"
  "        if (_108.x < 0.0)\n"
  "        {\n"
  "            float _480;\n"
  "            if (_108.y < 0.0)\n"
  "            {\n"
  "                _480 = in.v_radii.x;\n"
  "            }\n"
  "            else\n"
  "            {\n"
  "                _480 = in.v_radii.w;\n"
  "            }\n"
  "            _481 = _480;\n"
  "        }\n"
  "        else\n"
  "        {\n"
  "            float _479;\n"
  "            if (_108.y < 0.0)\n"
  "            {\n"
  "                _479 = in.v_radii.y;\n"
  "            }\n"
  "            else\n"
  "            {\n"
  "                _479 = in.v_radii.z;\n"
  "            }\n"
  "            _481 = _479;\n"
  "        }\n"
  "        float2 _286 = abs(_108) - (in.v_shape.zw - float2(_481));\n"
  "        float4 _444 = _101;\n"
  "        _444.w = _101.w * fast::clamp(0.5 - ((length(fast::max(_286, float2(0.0))) + fast::min(fast::max(_286.x, _286.y), 0.0)) - _481), 0.0, 1.0);\n"
  "        _485 = _444;\n"
  "    }\n"
  "    else\n"
  "    {\n"
  "        float4 _486;\n"
  "        if (_97 == 2)\n"
  "        {\n"
  "            float _475;\n"
  "            if (_108.x < 0.0)\n"
  "            {\n"
  "                float _474;\n"
  "                if (_108.y < 0.0)\n"
  "                {\n"
  "                    _474 = in.v_radii.x;\n"
  "                }\n"
  "                else\n"
  "                {\n"
  "                    _474 = in.v_radii.w;\n"
  "                }\n"
  "                _475 = _474;\n"
  "            }\n"
  "            else\n"
  "            {\n"
  "                float _473;\n"
  "                if (_108.y < 0.0)\n"
  "                {\n"
  "                    _473 = in.v_radii.y;\n"
  "                }\n"
  "                else\n"
  "                {\n"
  "                    _473 = in.v_radii.z;\n"
  "                }\n"
  "                _475 = _473;\n"
  "            }\n"
  "            float2 _338 = abs(_108);\n"
  "            float2 _343 = _338 - (in.v_shape.zw - float2(_475));\n"
  "            float _164 = fast::max(_475 - in.v_extra.x, 0.0);\n"
  "            float2 _366 = _338 - ((in.v_shape.zw - float2(in.v_extra.x)) - float2(_164));\n"
  "            float4 _454 = _101;\n"
  "            _454.w = _101.w * (fast::clamp(0.5 - ((length(fast::max(_343, float2(0.0))) + fast::min(fast::max(_343.x, _343.y), 0.0)) - _475), 0.0, 1.0) * (1.0 - fast::clamp(0.5 - ((length(fast::max(_366, float2(0.0))) + fast::min(fast::max(_366.x, _366.y), 0.0)) - _164), 0.0, 1.0)));\n"
  "            _486 = _454;\n"
  "        }\n"
  "        else\n"
  "        {\n"
  "            float4 _487;\n"
  "            if (_97 == 3)\n"
  "            {\n"
  "                float _469;\n"
  "                if (_108.x < 0.0)\n"
  "                {\n"
  "                    float _468;\n"
  "                    if (_108.y < 0.0)\n"
  "                    {\n"
  "                        _468 = in.v_radii.x;\n"
  "                    }\n"
  "                    else\n"
  "                    {\n"
  "                        _468 = in.v_radii.w;\n"
  "                    }\n"
  "                    _469 = _468;\n"
  "                }\n"
  "                else\n"
  "                {\n"
  "                    float _467;\n"
  "                    if (_108.y < 0.0)\n"
  "                    {\n"
  "                        _467 = in.v_radii.y;\n"
  "                    }\n"
  "                    else\n"
  "                    {\n"
  "                        _467 = in.v_radii.z;\n"
  "                    }\n"
  "                    _469 = _467;\n"
  "                }\n"
  "                float2 _423 = abs(_108) - (in.v_shape.zw - float2(_469));\n"
  "                float4 _462 = _101;\n"
  "                _462.w = _101.w * (1.0 - smoothstep(0.0, in.v_extra.x, (length(fast::max(_423, float2(0.0))) + fast::min(fast::max(_423.x, _423.y), 0.0)) - _469));\n"
  "                _487 = _462;\n"
  "            }\n"
  "            else\n"
  "            {\n"
  "                float4 _488;\n"
  "                if (_97 == 4)\n"
  "                {\n"
  "                    float4 _465 = _101;\n"
  "                    _465.w = _101.w * u_texture.sample(u_textureSmplr, in.v_uv).x;\n"
  "                    _488 = _465;\n"
  "                }\n"
  "                else\n"
  "                {\n"
  "                    float4 _489;\n"
  "                    if (_97 == 5)\n"
  "                    {\n"
  "                        _489 = _101 * u_texture.sample(u_textureSmplr, in.v_uv);\n"
  "                    }\n"
  "                    else\n"
  "                    {\n"
  "                        _489 = _101;\n"
  "                    }\n"
  "                    _488 = _489;\n"
  "                }\n"
  "                _487 = _488;\n"
  "            }\n"
  "            _486 = _487;\n"
  "        }\n"
  "        _485 = _486;\n"
  "    }\n"
  "    if (_485.w <= 0.0)\n"
  "    {\n"
  "        discard_fragment();\n"
  "    }\n"
  "    out.o_color = _485;\n"
  "    return out;\n"
  "}\n"
  "\n";
static const uint32_t re_ui_fragment_spv[] = {
  0x07230203u, 0x00010600u, 0x000d000bu, 0x000001ecu, 0x00000000u, 0x00020011u, 0x00000001u, 0x00020011u,
  0x00001503u, 0x0006000bu, 0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu,
  0x00000000u, 0x00000001u, 0x000d000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000003eu,
  0x0000005cu, 0x00000064u, 0x00000067u, 0x00000069u, 0x000000d3u, 0x000000d5u, 0x000000eeu, 0x00030010u,
  0x00000004u, 0x00000007u, 0x00030003u, 0x00000002u, 0x000001c2u, 0x000a0004u, 0x475f4c47u, 0x4c474f4fu,
  0x70635f45u, 0x74735f70u, 0x5f656c79u, 0x656e696cu, 0x7269645fu, 0x69746365u, 0x00006576u, 0x00080004u,
  0x475f4c47u, 0x4c474f4fu, 0x6e695f45u, 0x64756c63u, 0x69645f65u, 0x74636572u, 0x00657669u, 0x00040005u,
  0x00000004u, 0x6e69616du, 0x00000000u, 0x00040005u, 0x0000003eu, 0x61725f76u, 0x00696964u, 0x00040005u,
  0x0000005cu, 0x78655f76u, 0x00617274u, 0x00040005u, 0x00000064u, 0x6f635f76u, 0x00726f6cu, 0x00040005u,
  0x00000067u, 0x6f705f76u, 0x00000073u, 0x00040005u, 0x00000069u, 0x68735f76u, 0x00657061u, 0x00050005u,
  0x000000d3u, 0x65745f75u, 0x72757478u, 0x00000065u, 0x00040005u, 0x000000d5u, 0x76755f76u, 0x00000000u,
  0x00040005u, 0x000000eeu, 0x6f635f6fu, 0x00726f6cu, 0x00030047u, 0x0000003eu, 0x0000000eu, 0x00040047u,
  0x0000003eu, 0x0000001eu, 0x00000004u, 0x00030047u, 0x0000005cu, 0x0000000eu, 0x00040047u, 0x0000005cu,
  0x0000001eu, 0x00000005u, 0x00040047u, 0x00000064u, 0x0000001eu, 0x00000002u, 0x00040047u, 0x00000067u,
  0x0000001eu, 0x00000000u, 0x00030047u, 0x00000069u, 0x0000000eu, 0x00040047u, 0x00000069u, 0x0000001eu,
  0x00000003u, 0x00040047u, 0x000000d3u, 0x00000021u, 0x00000001u, 0x00040047u, 0x000000d3u, 0x00000022u,
  0x00000000u, 0x00040047u, 0x000000d5u, 0x0000001eu, 0x00000001u, 0x00040047u, 0x000000eeu, 0x0000001eu,
  0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u,
  0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u, 0x00000002u, 0x0004002bu, 0x00000006u, 0x0000001du,
  0x00000000u, 0x00040015u, 0x00000021u, 0x00000020u, 0x00000000u, 0x0004002bu, 0x00000021u, 0x00000022u,
  0x00000000u, 0x0004002bu, 0x00000021u, 0x00000025u, 0x00000001u, 0x00020014u, 0x00000031u, 0x00040017u,
  0x0000003cu, 0x00000006u, 0x00000004u, 0x00040020u, 0x0000003du, 0x00000001u, 0x0000003cu, 0x0004003bu,
  0x0000003du, 0x0000003eu, 0x00000001u, 0x00040020u, 0x0000003fu, 0x00000001u, 0x00000006u, 0x0004002bu,
  0x00000021u, 0x00000043u, 0x00000003u, 0x0004002bu, 0x00000021u, 0x00000051u, 0x00000002u, 0x00040015u,
  0x00000058u, 0x00000020u, 0x00000001u, 0x00040020u, 0x0000005bu, 0x00000001u, 0x00000007u, 0x0004003bu,
  0x0000005bu, 0x0000005cu, 0x00000001u, 0x0004002bu, 0x00000006u, 0x0000005fu, 0x3f000000u, 0x0004003bu,
  0x0000003du, 0x00000064u, 0x00000001u, 0x0004003bu, 0x0000005bu, 0x00000067u, 0x00000001u, 0x0004003bu,
  0x0000003du, 0x00000069u, 0x00000001u, 0x0004002bu, 0x00000058u, 0x00000074u, 0x00000001u, 0x0004002bu,
  0x00000006u, 0x00000082u, 0x3f800000u, 0x0004002bu, 0x00000058u, 0x0000008au, 0x00000002u, 0x0004002bu,
  0x00000058u, 0x000000b6u, 0x00000003u, 0x0004002bu, 0x00000058u, 0x000000ccu, 0x00000004u, 0x00090019u,
  0x000000d0u, 0x00000006u, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000001u, 0x00000000u,
  0x0003001bu, 0x000000d1u, 0x000000d0u, 0x00040020u, 0x000000d2u, 0x00000000u, 0x000000d1u, 0x0004003bu,
  0x000000d2u, 0x000000d3u, 0x00000000u, 0x0004003bu, 0x0000005bu, 0x000000d5u, 0x00000001u, 0x0004002bu,
  0x00000058u, 0x000000dfu, 0x00000005u, 0x00040020u, 0x000000edu, 0x00000003u, 0x0000003cu, 0x0004003bu,
  0x000000edu, 0x000000eeu, 0x00000003u, 0x0005002cu, 0x00000007u, 0x000001ebu, 0x0000001du, 0x0000001du,
  0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x00050041u,
  0x0000003fu, 0x0000005du, 0x0000005cu, 0x00000025u, 0x0004003du, 0x00000006u, 0x0000005eu, 0x0000005du,
  0x00050081u, 0x00000006u, 0x00000060u, 0x0000005eu, 0x0000005fu, 0x0004006eu, 0x00000058u, 0x00000061u,
  0x00000060u, 0x0004003du, 0x0000003cu, 0x00000065u, 0x00000064u, 0x0004003du, 0x00000007u, 0x00000068u,
  0x00000067u, 0x0004003du, 0x0000003cu, 0x0000006au, 0x00000069u, 0x0007004fu, 0x00000007u, 0x0000006bu,
  0x0000006au, 0x0000006au, 0x00000000u, 0x00000001u, 0x00050083u, 0x00000007u, 0x0000006cu, 0x00000068u,
  0x0000006bu, 0x0007004fu, 0x00000007u, 0x0000006fu, 0x0000006au, 0x0000006au, 0x00000002u, 0x00000003u,
  0x00050041u, 0x0000003fu, 0x00000071u, 0x0000005cu, 0x00000022u, 0x0004003du, 0x00000006u, 0x00000072u,
  0x00000071u, 0x000500aau, 0x00000031u, 0x00000075u, 0x00000061u, 0x00000074u, 0x000300f7u, 0x00000077u,
  0x00000000u, 0x000400fau, 0x00000075u, 0x00000076u, 0x00000088u, 0x000200f8u, 0x00000076u, 0x00050051u,
  0x00000006u, 0x000000f9u, 0x0000006cu, 0x00000000u, 0x000500b8u, 0x00000031u, 0x000000fau, 0x000000f9u,
  0x0000001du, 0x000300f7u, 0x00000113u, 0x00000000u, 0x000400fau, 0x000000fau, 0x000000fbu, 0x00000107u,
  0x000200f8u, 0x000000fbu, 0x00050051u, 0x00000006u, 0x000000fdu, 0x0000006cu, 0x00000001u, 0x000500b8u,
  0x00000031u, 0x000000feu, 0x000000fdu, 0x0000001du, 0x000300f7u, 0x00000105u, 0x00000000u, 0x000400fau,
  0x000000feu, 0x000000ffu, 0x00000102u, 0x000200f8u, 0x000000ffu, 0x00050041u, 0x0000003fu, 0x00000100u,
  0x0000003eu, 0x00000022u, 0x0004003du, 0x00000006u, 0x00000101u, 0x00000100u, 0x000200f9u, 0x00000105u,
  0x000200f8u, 0x00000102u, 0x00050041u, 0x0000003fu, 0x00000103u, 0x0000003eu, 0x00000043u, 0x0004003du,
  0x00000006u, 0x00000104u, 0x00000103u, 0x000200f9u, 0x00000105u, 0x000200f8u, 0x00000105u, 0x000700f5u,
  0x00000006u, 0x000001e0u, 0x00000101u, 0x000000ffu, 0x00000104u, 0x00000102u, 0x000200f9u, 0x00000113u,
  0x000200f8u, 0x00000107u, 0x00050051u, 0x00000006u, 0x00000109u, 0x0000006cu, 0x00000001u, 0x000500b8u,
  0x00000031u, 0x0000010au, 0x00000109u, 0x0000001du, 0x000300f7u, 0x00000111u, 0x00000000u, 0x000400fau,
  0x0000010au, 0x0000010bu, 0x0000010eu, 0x000200f8u, 0x0000010bu, 0x00050041u, 0x0000003fu, 0x0000010cu,
  0x0000003eu, 0x00000025u, 0x0004003du, 0x00000006u, 0x0000010du, 0x0000010cu, 0x000200f9u, 0x00000111u,
  0x000200f8u, 0x0000010eu, 0x00050041u, 0x0000003fu, 0x0000010fu, 0x0000003eu, 0x00000051u, 0x0004003du,
  0x00000006u, 0x00000110u, 0x0000010fu, 0x000200f9u, 0x00000111u, 0x000200f8u, 0x00000111u, 0x000700f5u,
  0x00000006u, 0x000001dfu, 0x0000010du, 0x0000010bu, 0x00000110u, 0x0000010eu, 0x000200f9u, 0x00000113u,
  0x000200f8u, 0x00000113u, 0x000700f5u, 0x00000006u, 0x000001e1u, 0x000001e0u, 0x00000105u, 0x000001dfu,
  0x00000111u, 0x0006000cu, 0x00000007u, 0x00000119u, 0x00000001u, 0x00000004u, 0x0000006cu, 0x00050050u,
  0x00000007u, 0x0000011cu, 0x000001e1u, 0x000001e1u, 0x00050083u, 0x00000007u, 0x0000011du, 0x0000006fu,
  0x0000011cu, 0x00050083u, 0x00000007u, 0x0000011eu, 0x00000119u, 0x0000011du, 0x0007000cu, 0x00000007u,
  0x00000121u, 0x00000001u, 0x00000028u, 0x0000011eu, 0x000001ebu, 0x0006000cu, 0x00000006u, 0x00000122u,
  0x00000001u, 0x00000042u, 0x00000121u, 0x00050051u, 0x00000006u, 0x00000124u, 0x0000011eu, 0x00000000u,
  0x00050051u, 0x00000006u, 0x00000126u, 0x0000011eu, 0x00000001u, 0x0007000cu, 0x00000006u, 0x00000127u,
  0x00000001u, 0x00000028u, 0x00000124u, 0x00000126u, 0x0007000cu, 0x00000006u, 0x00000128u, 0x00000001u,
  0x00000025u, 0x00000127u, 0x0000001du, 0x00050081u, 0x00000006u, 0x00000129u, 0x00000122u, 0x00000128u,
  0x00050083u, 0x00000006u, 0x0000012bu, 0x00000129u, 0x000001e1u, 0x00050083u, 0x00000006u, 0x00000081u,
  0x0000005fu, 0x0000012bu, 0x0008000cu, 0x00000006u, 0x00000083u, 0x00000001u, 0x0000002bu, 0x00000081u,
  0x0000001du, 0x00000082u, 0x00050051u, 0x00000006u, 0x00000085u, 0x00000065u, 0x00000003u, 0x00050085u,
  0x00000006u, 0x00000086u, 0x00000085u, 0x00000083u, 0x00060052u, 0x0000003cu, 0x000001bcu, 0x00000086u,
  0x00000065u, 0x00000003u, 0x000200f9u, 0x00000077u, 0x000200f8u, 0x00000088u, 0x000500aau, 0x00000031u,
  0x0000008bu, 0x00000061u, 0x0000008au, 0x000300f7u, 0x0000008du, 0x00000000u, 0x000400fau, 0x0000008bu,
  0x0000008cu, 0x000000b4u, 0x000200f8u, 0x0000008cu, 0x00050051u, 0x00000006u, 0x00000132u, 0x0000006cu,
  0x00000000u, 0x000500b8u, 0x00000031u, 0x00000133u, 0x00000132u, 0x0000001du, 0x000300f7u, 0x0000014cu,
  0x00000000u, 0x000400fau, 0x00000133u, 0x00000134u, 0x00000140u, 0x000200f8u, 0x00000134u, 0x00050051u,
  0x00000006u, 0x00000136u, 0x0000006cu, 0x00000001u, 0x000500b8u, 0x00000031u, 0x00000137u, 0x00000136u,
  0x0000001du, 0x000300f7u, 0x0000013eu, 0x00000000u, 0x000400fau, 0x00000137u, 0x00000138u, 0x0000013bu,
  0x000200f8u, 0x00000138u, 0x00050041u, 0x0000003fu, 0x00000139u, 0x0000003eu, 0x00000022u, 0x0004003du,
  0x00000006u, 0x0000013au, 0x00000139u, 0x000200f9u, 0x0000013eu, 0x000200f8u, 0x0000013bu, 0x00050041u,
  0x0000003fu, 0x0000013cu, 0x0000003eu, 0x00000043u, 0x0004003du, 0x00000006u, 0x0000013du, 0x0000013cu,
  0x000200f9u, 0x0000013eu, 0x000200f8u, 0x0000013eu, 0x000700f5u, 0x00000006u, 0x000001dau, 0x0000013au,
  0x00000138u, 0x0000013du, 0x0000013bu, 0x000200f9u, 0x0000014cu, 0x000200f8u, 0x00000140u, 0x00050051u,
  0x00000006u, 0x00000142u, 0x0000006cu, 0x00000001u, 0x000500b8u, 0x00000031u, 0x00000143u, 0x00000142u,
  0x0000001du, 0x000300f7u, 0x0000014au, 0x00000000u, 0x000400fau, 0x00000143u, 0x00000144u, 0x00000147u,
  0x000200f8u, 0x00000144u, 0x00050041u, 0x0000003fu, 0x00000145u, 0x0000003eu, 0x00000025u, 0x0004003du,
  0x00000006u, 0x00000146u, 0x00000145u, 0x000200f9u, 0x0000014au, 0x000200f8u, 0x00000147u, 0x00050041u,
  0x0000003fu, 0x00000148u, 0x0000003eu, 0x00000051u, 0x0004003du, 0x00000006u, 0x00000149u, 0x00000148u,
  0x000200f9u, 0x0000014au, 0x000200f8u, 0x0000014au, 0x000700f5u, 0x00000006u, 0x000001d9u, 0x00000146u,
  0x00000144u, 0x00000149u, 0x00000147u, 0x000200f9u, 0x0000014cu, 0x000200f8u, 0x0000014cu, 0x000700f5u,
  0x00000006u, 0x000001dbu, 0x000001dau, 0x0000013eu, 0x000001d9u, 0x0000014au, 0x0006000cu, 0x00000007u,
  0x00000152u, 0x00000001u, 0x00000004u, 0x0000006cu, 0x00050050u, 0x00000007u, 0x00000155u, 0x000001dbu,
  0x000001dbu, 0x00050083u, 0x00000007u, 0x00000156u, 0x0000006fu, 0x00000155u, 0x00050083u, 0x00000007u,
  0x00000157u, 0x00000152u, 0x00000156u, 0x0007000cu, 0x00000007u, 0x0000015au, 0x00000001u, 0x00000028u,
  0x00000157u, 0x000001ebu, 0x0006000cu, 0x00000006u, 0x0000015bu, 0x00000001u, 0x00000042u, 0x0000015au,
  0x00050051u, 0x00000006u, 0x0000015du, 0x00000157u, 0x00000000u, 0x00050051u, 0x00000006u, 0x0000015fu,
  0x00000157u, 0x00000001u, 0x0007000cu, 0x00000006u, 0x00000160u, 0x00000001u, 0x00000028u, 0x0000015du,
  0x0000015fu, 0x0007000cu, 0x00000006u, 0x00000161u, 0x00000001u, 0x00000025u, 0x00000160u, 0x0000001du,
  0x00050081u, 0x00000006u, 0x00000162u, 0x0000015bu, 0x00000161u, 0x00050083u, 0x00000006u, 0x00000164u,
  0x00000162u, 0x000001dbu, 0x00050083u, 0x00000006u, 0x0000009au, 0x0000005fu, 0x00000164u, 0x0008000cu,
  0x00000006u, 0x0000009bu, 0x00000001u, 0x0000002bu, 0x0000009au, 0x0000001du, 0x00000082u, 0x00050050u,
  0x00000007u, 0x0000009fu, 0x00000072u, 0x00000072u, 0x00050083u, 0x00000007u, 0x000000a0u, 0x0000006fu,
  0x0000009fu, 0x00050083u, 0x00000006u, 0x000000a3u, 0x000001dbu, 0x00000072u, 0x0007000cu, 0x00000006u,
  0x000000a4u, 0x00000001u, 0x00000028u, 0x000000a3u, 0x0000001du, 0x00050050u, 0x00000007u, 0x0000016cu,
  0x000000a4u, 0x000000a4u, 0x00050083u, 0x00000007u, 0x0000016du, 0x000000a0u, 0x0000016cu, 0x00050083u,
  0x00000007u, 0x0000016eu, 0x00000152u, 0x0000016du, 0x0007000cu, 0x00000007u, 0x00000171u, 0x00000001u,
  0x00000028u, 0x0000016eu, 0x000001ebu, 0x0006000cu, 0x00000006u, 0x00000172u, 0x00000001u, 0x00000042u,
  0x00000171u, 0x00050051u, 0x00000006u, 0x00000174u, 0x0000016eu, 0x00000000u, 0x00050051u, 0x00000006u,
  0x00000176u, 0x0000016eu, 0x00000001u, 0x0007000cu, 0x00000006u, 0x00000177u, 0x00000001u, 0x00000028u,
  0x00000174u, 0x00000176u, 0x0007000cu, 0x00000006u, 0x00000178u, 0x00000001u, 0x00000025u, 0x00000177u,
  0x0000001du, 0x00050081u, 0x00000006u, 0x00000179u, 0x00000172u, 0x00000178u, 0x00050083u, 0x00000006u,
  0x0000017bu, 0x00000179u, 0x000000a4u, 0x00050083u, 0x00000006u, 0x000000aau, 0x0000005fu, 0x0000017bu,
  0x0008000cu, 0x00000006u, 0x000000abu, 0x00000001u, 0x0000002bu, 0x000000aau, 0x0000001du, 0x00000082u,
  0x00050083u, 0x00000006u, 0x000000aeu, 0x00000082u, 0x000000abu, 0x00050085u, 0x00000006u, 0x000000afu,
  0x0000009bu, 0x000000aeu, 0x00050051u, 0x00000006u, 0x000000b1u, 0x00000065u, 0x00000003u, 0x00050085u,
  0x00000006u, 0x000000b2u, 0x000000b1u, 0x000000afu, 0x00060052u, 0x0000003cu, 0x000001c6u, 0x000000b2u,
  0x00000065u, 0x00000003u, 0x000200f9u, 0x0000008du, 0x000200f8u, 0x000000b4u, 0x000500aau, 0x00000031u,
  0x000000b7u, 0x00000061u, 0x000000b6u, 0x000300f7u, 0x000000b9u, 0x00000000u, 0x000400fau, 0x000000b7u,
  0x000000b8u, 0x000000cau, 0x000200f8u, 0x000000b8u, 0x00050051u, 0x00000006u, 0x00000182u, 0x0000006cu,
  0x00000000u, 0x000500b8u, 0x00000031u, 0x00000183u, 0x00000182u, 0x0000001du, 0x000300f7u, 0x0000019cu,
  0x00000000u, 0x000400fau, 0x00000183u, 0x00000184u, 0x00000190u, 0x000200f8u, 0x00000184u, 0x00050051u,
  0x00000006u, 0x00000186u, 0x0000006cu, 0x00000001u, 0x000500b8u, 0x00000031u, 0x00000187u, 0x00000186u,
  0x0000001du, 0x000300f7u, 0x0000018eu, 0x00000000u, 0x000400fau, 0x00000187u, 0x00000188u, 0x0000018bu,
  0x000200f8u, 0x00000188u, 0x00050041u, 0x0000003fu, 0x00000189u, 0x0000003eu, 0x00000022u, 0x0004003du,
  0x00000006u, 0x0000018au, 0x00000189u, 0x000200f9u, 0x0000018eu, 0x000200f8u, 0x0000018bu, 0x00050041u,
  0x0000003fu, 0x0000018cu, 0x0000003eu, 0x00000043u, 0x0004003du, 0x00000006u, 0x0000018du, 0x0000018cu,
  0x000200f9u, 0x0000018eu, 0x000200f8u, 0x0000018eu, 0x000700f5u, 0x00000006u, 0x000001d4u, 0x0000018au,
  0x00000188u, 0x0000018du, 0x0000018bu, 0x000200f9u, 0x0000019cu, 0x000200f8u, 0x00000190u, 0x00050051u,
  0x00000006u, 0x00000192u, 0x0000006cu, 0x00000001u, 0x000500b8u, 0x00000031u, 0x00000193u, 0x00000192u,
  0x0000001du, 0x000300f7u, 0x0000019au, 0x00000000u, 0x000400fau, 0x00000193u, 0x00000194u, 0x00000197u,
  0x000200f8u, 0x00000194u, 0x00050041u, 0x0000003fu, 0x00000195u, 0x0000003eu, 0x00000025u, 0x0004003du,
  0x00000006u, 0x00000196u, 0x00000195u, 0x000200f9u, 0x0000019au, 0x000200f8u, 0x00000197u, 0x00050041u,
  0x0000003fu, 0x00000198u, 0x0000003eu, 0x00000051u, 0x0004003du, 0x00000006u, 0x00000199u, 0x00000198u,
  0x000200f9u, 0x0000019au, 0x000200f8u, 0x0000019au, 0x000700f5u, 0x00000006u, 0x000001d3u, 0x00000196u,
  0x00000194u, 0x00000199u, 0x00000197u, 0x000200f9u, 0x0000019cu, 0x000200f8u, 0x0000019cu, 0x000700f5u,
  0x00000006u, 0x000001d5u, 0x000001d4u, 0x0000018eu, 0x000001d3u, 0x0000019au, 0x0006000cu, 0x00000007u,
  0x000001a2u, 0x00000001u, 0x00000004u, 0x0000006cu, 0x00050050u, 0x00000007u, 0x000001a5u, 0x000001d5u,
  0x000001d5u, 0x00050083u, 0x00000007u, 0x000001a6u, 0x0000006fu, 0x000001a5u, 0x00050083u, 0x00000007u,
  0x000001a7u, 0x000001a2u, 0x000001a6u, 0x0007000cu, 0x00000007u, 0x000001aau, 0x00000001u, 0x00000028u,
  0x000001a7u, 0x000001ebu, 0x0006000cu, 0x00000006u, 0x000001abu, 0x00000001u, 0x00000042u, 0x000001aau,
  0x00050051u, 0x00000006u, 0x000001adu, 0x000001a7u, 0x00000000u, 0x00050051u, 0x00000006u, 0x000001afu,
  0x000001a7u, 0x00000001u, 0x0007000cu, 0x00000006u, 0x000001b0u, 0x00000001u, 0x00000028u, 0x000001adu,
  0x000001afu, 0x0007000cu, 0x00000006u, 0x000001b1u, 0x00000001u, 0x00000025u, 0x000001b0u, 0x0000001du,
  0x00050081u, 0x00000006u, 0x000001b2u, 0x000001abu, 0x000001b1u, 0x00050083u, 0x00000006u, 0x000001b4u,
  0x000001b2u, 0x000001d5u, 0x0008000cu, 0x00000006u, 0x000000c4u, 0x00000001u, 0x00000031u, 0x0000001du,
  0x00000072u, 0x000001b4u, 0x00050083u, 0x00000006u, 0x000000c5u, 0x00000082u, 0x000000c4u, 0x00050051u,
  0x00000006u, 0x000000c7u, 0x00000065u, 0x00000003u, 0x00050085u, 0x00000006u, 0x000000c8u, 0x000000c7u,
  0x000000c5u, 0x00060052u, 0x0000003cu, 0x000001ceu, 0x000000c8u, 0x00000065u, 0x00000003u, 0x000200f9u,
  0x000000b9u, 0x000200f8u, 0x000000cau, 0x000500aau, 0x00000031u, 0x000000cdu, 0x00000061u, 0x000000ccu,
  0x000300f7u, 0x000000cfu, 0x00000000u, 0x000400fau, 0x000000cdu, 0x000000ceu, 0x000000ddu, 0x000200f8u,
  0x000000ceu, 0x0004003du, 0x000000d1u, 0x000000d4u, 0x000000d3u, 0x0004003du, 0x00000007u, 0x000000d6u,
  0x000000d5u, 0x00050057u, 0x0000003cu, 0x000000d7u, 0x000000d4u, 0x000000d6u, 0x00050051u, 0x00000006u,
  0x000000d8u, 0x000000d7u, 0x00000000u, 0x00050051u, 0x00000006u, 0x000000dau, 0x00000065u, 0x00000003u,
  0x00050085u, 0x00000006u, 0x000000dbu, 0x000000dau, 0x000000d8u, 0x00060052u, 0x0000003cu, 0x000001d1u,
  0x000000dbu, 0x00000065u, 0x00000003u, 0x000200f9u, 0x000000cfu, 0x000200f8u, 0x000000ddu, 0x000500aau,
  0x00000031u, 0x000000e0u, 0x00000061u, 0x000000dfu, 0x000300f7u, 0x000000e2u, 0x00000000u, 0x000400fau,
  0x000000e0u, 0x000000e1u, 0x000000e2u, 0x000200f8u, 0x000000e1u, 0x0004003du, 0x000000d1u, 0x000000e3u,
  0x000000d3u, 0x0004003du, 0x00000007u, 0x000000e4u, 0x000000d5u, 0x00050057u, 0x0000003cu, 0x000000e5u,
  0x000000e3u, 0x000000e4u, 0x00050085u, 0x0000003cu, 0x000000e7u, 0x00000065u, 0x000000e5u, 0x000200f9u,
  0x000000e2u, 0x000200f8u, 0x000000e2u, 0x000700f5u, 0x0000003cu, 0x000001e9u, 0x00000065u, 0x000000ddu,
  0x000000e7u, 0x000000e1u, 0x000200f9u, 0x000000cfu, 0x000200f8u, 0x000000cfu, 0x000700f5u, 0x0000003cu,
  0x000001e8u, 0x000001d1u, 0x000000ceu, 0x000001e9u, 0x000000e2u, 0x000200f9u, 0x000000b9u, 0x000200f8u,
  0x000000b9u, 0x000700f5u, 0x0000003cu, 0x000001e7u, 0x000001ceu, 0x0000019cu, 0x000001e8u, 0x000000cfu,
  0x000200f9u, 0x0000008du, 0x000200f8u, 0x0000008du, 0x000700f5u, 0x0000003cu, 0x000001e6u, 0x000001c6u,
  0x0000014cu, 0x000001e7u, 0x000000b9u, 0x000200f9u, 0x00000077u, 0x000200f8u, 0x00000077u, 0x000700f5u,
  0x0000003cu, 0x000001e5u, 0x000001bcu, 0x00000113u, 0x000001e6u, 0x0000008du, 0x00050051u, 0x00000006u,
  0x000000e9u, 0x000001e5u, 0x00000003u, 0x000500bcu, 0x00000031u, 0x000000eau, 0x000000e9u, 0x0000001du,
  0x000300f7u, 0x000000ecu, 0x00000000u, 0x000400fau, 0x000000eau, 0x000000ebu, 0x000000ecu, 0x000200f8u,
  0x000000ebu, 0x00011504u, 0x000200f9u, 0x000000ecu, 0x000200f8u, 0x000000ecu, 0x0003003eu, 0x000000eeu,
  0x000001e5u, 0x000100fdu, 0x00010038u,
};

#endif
