/* Generated by `python3 tools/design.py generate` from orchestrator/native/icons.json. Edit the mapping, not this file. */
#ifndef RENGINE_ICONS_H
#define RENGINE_ICONS_H
#include <stdint.h>
/* Face: Phosphor 2.1.2 (third_party/phosphor/Phosphor.ttf) */
enum {
  RE_ICON_UNKNOWN = 0,
  RE_ICON_CLOSE = 1,
  RE_ICON_CHECK = 2,
  RE_ICON_COLLAPSED = 3,
  RE_ICON_EXPANDED = 4,
  RE_ICON_TREE = 5,
  RE_ICON_SHELL = 6,
  RE_ICON_AGENT = 7,
  RE_ICON_SPLIT_VERTICAL = 8,
  RE_ICON_SPLIT_HORIZONTAL = 9,
  RE_ICON_MERGE_PANE = 10,
  RE_ICON_PROJECT = 11,
  RE_ICON_SEARCH = 12,
  RE_ICON_THEME = 13,
  RE_ICON_DIRTY = 14,
  RE_ICON_HOLLOW = 15,
  RE_ICON_ADD = 16,
  RE_ICON_ARROW_UP = 17,
  RE_ICON_CARET_UP = 18,
  RE_ICON_CARET_LEFT = 19,
  RE_ICON_MENU = 20,
  RE_ICON_RUN = 21,
  RE_ICON_FILE = 22,
  RE_ICON_FOLDER_OPEN = 23,
  RE_ICON_COUNT = 24
};
static const uint32_t re_icon_codepoints[RE_ICON_COUNT] = {
  0xe650, /* placeholder */
  0xe4f6, /* x — ✕ */
  0xe182, /* check */
  0xe13a, /* caret-right — ▸ › */
  0xe136, /* caret-down — ▾ */
  0xec24, /* sidebar-simple — ⊟ */
  0xeae8, /* terminal-window — ›_ */
  0xe1ec, /* diamond — ◆ */
  0xe546, /* columns — ▯▯ */
  0xe5a2, /* rows — ▭ */
  0xe69a, /* selection — ⊡ */
  0xe24a, /* folder — ▣ */
  0xe30c, /* magnifying-glass — ⌕ */
  0xe18c, /* circle-half — ◐ ◑ */
  0xecde, /* dot — ▪ ● */
  0xece0, /* dot-outline — ▫ */
  0xe3d4, /* plus — + */
  0xe08e, /* arrow-up — ↑ */
  0xe13c, /* caret-up — ▲ */
  0xe138, /* caret-left — ‹ */
  0xe2f0, /* list — ≡ */
  0xe3d0, /* play — ▶ */
  0xe230, /* file */
  0xe256, /* folder-open */
};
#endif
