/* GENERATED by tools/seam_prefix.py -- do not edit. Regenerate with `python3 tools/seam_prefix.py generate`.
 *
 * Force-included into the opengl copy of the seam, rEngine's draw-list backend and its host, so
 * that copy defines and calls re_opengl_-prefixed symbols and three copies link into one binary
 * (spec 124, spec 126 decision 3). The pack's own sources are unmodified; this is applied
 * from the build with -include (/FI on MSVC).
 */
#ifndef RENGINE_SEAM_PREFIX_OPENGL_H
#define RENGINE_SEAM_PREFIX_OPENGL_H

#define re_backend_seam_open         re_opengl_backend_seam_open
#define re_backend_seam_window_flags re_opengl_backend_seam_window_flags
#define re_gpu_close                 re_opengl_gpu_close
#define re_gpu_device                re_opengl_gpu_device
#define re_gpu_device_name           re_opengl_gpu_device_name
#define re_gpu_device_proc           re_opengl_gpu_device_proc
#define re_gpu_family                re_opengl_gpu_family
#define re_gpu_instance              re_opengl_gpu_instance
#define re_gpu_instance_proc         re_opengl_gpu_instance_proc
#define re_gpu_memory_type           re_opengl_gpu_memory_type
#define re_gpu_open                  re_opengl_gpu_open
#define re_gpu_physical              re_opengl_gpu_physical
#define re_gpu_portability_subset    re_opengl_gpu_portability_subset
#define re_gpu_queue                 re_opengl_gpu_queue
#define re_seam_api_version          re_opengl_seam_api_version
#define re_seam_backend              re_opengl_seam_backend
#define re_seam_blend                re_opengl_seam_blend
#define re_seam_blend_separate       re_opengl_seam_blend_separate
#define re_seam_buffer               re_opengl_seam_buffer
#define re_seam_buffer_destroy       re_opengl_seam_buffer_destroy
#define re_seam_buffer_update        re_opengl_seam_buffer_update
#define re_seam_clear                re_opengl_seam_clear
#define re_seam_close                re_opengl_seam_close
#define re_seam_cull                 re_opengl_seam_cull
#define re_seam_current              re_opengl_seam_current
#define re_seam_depth                re_opengl_seam_depth
#define re_seam_depth_compare        re_opengl_seam_depth_compare
#define re_seam_draw                 re_opengl_seam_draw
#define re_seam_frame_begin          re_opengl_seam_frame_begin
#define re_seam_frame_end            re_opengl_seam_frame_end
#define re_seam_host_acquire         re_opengl_seam_host_acquire
#define re_seam_host_close           re_opengl_seam_host_close
#define re_seam_host_flags           re_opengl_seam_host_flags
#define re_seam_host_name            re_opengl_seam_host_name
#define re_seam_host_open            re_opengl_seam_host_open
#define re_seam_host_present         re_opengl_seam_host_present
#define re_seam_host_seam            re_opengl_seam_host_seam
#define re_seam_host_size            re_opengl_seam_host_size
#define re_seam_host_snapshot        re_opengl_seam_host_snapshot
#define re_seam_make_current         re_opengl_seam_make_current
#define re_seam_open                 re_opengl_seam_open
#define re_seam_program              re_opengl_seam_program
#define re_seam_program_destroy      re_opengl_seam_program_destroy
#define re_seam_program_use          re_opengl_seam_program_use
#define re_seam_scissor              re_opengl_seam_scissor
#define re_seam_target               re_opengl_seam_target
#define re_seam_target_adopt         re_opengl_seam_target_adopt
#define re_seam_target_bind          re_opengl_seam_target_bind
#define re_seam_target_destroy       re_opengl_seam_target_destroy
#define re_seam_texture_2d           re_opengl_seam_texture_2d
#define re_seam_texture_2d_for       re_opengl_seam_texture_2d_for
#define re_seam_texture_bind         re_opengl_seam_texture_bind
#define re_seam_texture_destroy      re_opengl_seam_texture_destroy
#define re_seam_texture_handle       re_opengl_seam_texture_handle
#define re_seam_texture_update       re_opengl_seam_texture_update
#define re_seam_uniform_float        re_opengl_seam_uniform_float
#define re_seam_uniform_int          re_opengl_seam_uniform_int
#define re_seam_uniform_location     re_opengl_seam_uniform_location
#define re_seam_uniform_mat4         re_opengl_seam_uniform_mat4
#define re_seam_uniform_vec2         re_opengl_seam_uniform_vec2
#define re_seam_uniform_vec4         re_opengl_seam_uniform_vec4
#define re_seam_vertex_array         re_opengl_seam_vertex_array
#define re_seam_vertex_array_bind    re_opengl_seam_vertex_array_bind
#define re_seam_vertex_array_destroy re_opengl_seam_vertex_array_destroy
#define re_seam_viewport             re_opengl_seam_viewport
#define re_seam_vk_report            re_opengl_seam_vk_report
#define re_spirv_reflect             re_opengl_spirv_reflect

#endif
