import test from 'node:test';
import assert from 'node:assert/strict';
import { _electron, expect } from '@playwright/test';
import { mkdtemp, writeFile, readFile, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { startServer } from '../server/main.mjs';
import { dragTab } from './drag.mjs';

test('desktop tree/editor saves, retains drafts and reattaches a terminal after GUI restart', { timeout: 90000 }, async t => {
  const dir = await mkdtemp(path.join(tmpdir(), 'rengine-desktop-'));
  await writeFile(path.join(dir, 'README.md'), '# Desktop fixture\n');
  const server = await startServer({ stateDir: path.join(dir, 'state') });
  const root = await server.store.addRoot(dir);
  const originalShell = process.env.SHELL;
  if (process.platform !== 'win32') process.env.SHELL = '/bin/bash';
  let app;
  t.after(async () => { if (originalShell === undefined) delete process.env.SHELL; else process.env.SHELL = originalShell;
    await app?.close().catch(() => {}); await server.close(); await rm(dir, { recursive: true, force: true }); });
  const launch = async () => {
    app = await _electron.launch({ args: [path.resolve('orchestrator/desktop/main.cjs')],
      env: { ...process.env, RENGINE_UI_URL: `${server.url}/#${server.token}`, RENGINE_DESKTOP_STATE: path.join(dir, 'electron') } });
    const page = await app.firstWindow();
    page.on('pageerror', error => t.diagnostic(error.message));
    await expect(page.getByRole('button', { name: 'New terminal', exact: true })).toBeVisible();
    return page;
  };
  let page = await launch();
  await page.getByRole('button', { name: 'README.md', exact: true }).click();
  const editor = page.locator('.cm-content');
  await expect(editor).toContainText('Desktop fixture');
  await editor.fill('# Saved through the actual editor\n');
  await page.getByRole('button', { name: 'Save file', exact: true }).click();
  await expect.poll(() => readFile(path.join(dir, 'README.md'), 'utf8')).toBe('# Saved through the actual editor\n');
  await writeFile(path.join(dir, 'README.md'), '# External edit\nSecond line\n');
  await editor.fill('# Stale editor version\n');
  await page.getByRole('button', { name: 'Save file', exact: true }).click();
  await expect(page.getByText('The file changed on disk. Your draft is retained.')).toBeVisible();
  assert.equal(await readFile(path.join(dir, 'README.md'), 'utf8'), '# External edit\nSecond line\n');
  await page.getByRole('button', { name: 'Discard & reload', exact: true }).click();
  await expect(editor).toContainText('External edit');
  await page.getByRole('checkbox', { name: 'Vim mode', exact: true }).check();
  await editor.click();
  await page.keyboard.press('Escape');
  await page.keyboard.type('ggdd');
  await expect(editor).not.toContainText('External edit');
  await expect(editor).toContainText('Second line');
  await page.getByRole('checkbox', { name: 'Vim mode', exact: true }).uncheck();
  await editor.fill('# Draft survives the GUI\n');
  await page.getByRole('button', { name: 'New terminal', exact: true }).click();
  await expect.poll(() => server.sessions.list().length).toBe(1);
  const session = server.sessions.list()[0];
  await page.locator('.xterm-helper-textarea').focus();
  await page.keyboard.type(process.platform === 'win32' ? "Write-Output ('DESKTOP_' + 'INPUT_OK')" : "printf '\\nDESKTOP_%s\\n' INPUT_OK");
  await page.keyboard.press('Enter');
  await expect.poll(() => server.sessions.snapshot(session.id, true).output).toContain('DESKTOP_INPUT_OK');
  await page.getByRole('button', { name: 'Split right', exact: true }).click();
  const destination = await dragTab(page, page.locator('.flexlayout__tab_button').filter({ hasText: 'Terminal ·' }), page.locator('.empty-pane').last());
  await expect.poll(async () => (await page.locator('.terminal.pane').boundingBox()).x).toBeGreaterThanOrEqual(destination.x - 2);
  assert.equal(server.sessions.list()[0].pid, session.pid);
  await app.close();
  assert.equal(server.sessions.get(session.id).state, 'running');
  assert.equal(server.store.getDraft(root.id, 'README.md').text, '# Draft survives the GUI\n');
  page = await launch();
  await page.getByRole('button', { name: 'README.md', exact: true }).click();
  await expect(page.locator('.cm-content:visible')).toContainText('Draft survives the GUI');
  await page.getByRole('button', { name: 'Session browser', exact: true }).click();
  await expect(page.getByText(String(session.pid), { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Attach', exact: true }).click();
  assert.equal(server.sessions.list()[0].pid, session.pid);
  await mkdir('.cache/evidence', { recursive: true });
  await page.screenshot({ path: '.cache/evidence/desktop-foundation.png' });
});
