import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { startServer } from '../server/main.mjs';
import { WebSocket } from 'ws';
import { once } from 'node:events';

test('real MCP stdio tools keep files and sessions bound to the original project', { timeout: 15000 }, async t => {
  const directory = await mkdtemp(path.join(tmpdir(), 'rengine-mcp-'));
  await mkdir(path.join(directory, 'a')); await mkdir(path.join(directory, 'b'));
  await writeFile(path.join(directory, 'a/same.txt'), 'Root A\nsecond\n');
  await writeFile(path.join(directory, 'b/same.txt'), 'Root B\n');
  const server = await startServer({ stateDir: path.join(directory, 'state') });
  const a = await server.store.addRoot(path.join(directory, 'a'));
  const b = await server.store.addRoot(path.join(directory, 'b'));
  const contextFile = path.join(directory, 'context.json');
  await writeFile(contextFile, JSON.stringify({ url: server.url, token: server.token, instance: server.instance, rootId: a.id }), { mode: 0o600 });
  const client = new Client({ name: 'rengine-test', version: '1.0.0' });
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.resolve('orchestrator/agents/mcp.mjs'), '--context', contextFile], stderr: 'pipe' });
  t.after(async () => { await client.close(); await server.close(); await rm(directory, { recursive: true, force: true }); });
  await client.connect(transport);
  const tools = await client.listTools();
  assert.ok(tools.tools.some(tool => tool.name === 'workspace_info'));
  assert.ok(tools.tools.some(tool => tool.name === 'list_desktops'));
  assert.ok(tools.tools.some(tool => tool.name === 'reload_desktop'));
  const info = await client.callTool({ name: 'workspace_info', arguments: {} });
  assert.equal(info.isError, undefined);
  assert.equal(JSON.parse(info.content[0].text).root.id, a.id);
  const file = await client.callTool({ name: 'read_file', arguments: { path: 'same.txt', startLine: 1, maxLines: 1 } });
  assert.equal(JSON.parse(file.content[0].text).text, 'Root A');
  const traversal = await client.callTool({ name: 'read_file', arguments: { path: '../b/same.txt' } });
  assert.equal(traversal.isError, true);
  const foreign = await server.sessions.terminal({ rootId: b.id, ...(process.platform === 'win32' ? { command: 'cmd.exe', args: [] } : { command: '/bin/bash', args: ['--noprofile', '--norc'] }) });
  const denied = await client.callTool({ name: 'session_output', arguments: { id: foreign.id } });
  assert.equal(denied.isError, true);
  const stop = await client.callTool({ name: 'stop_session', arguments: { id: foreign.id } });
  assert.equal(stop.isError, true);
  assert.equal(server.sessions.get(foreign.id).state, 'running');
  const desktop = new WebSocket(`${server.url.replace('http', 'ws')}/events?token=${server.token}`);
  t.after(() => desktop.terminate()); await once(desktop, 'open');
  const registration = new Promise(resolve => desktop.on('message', bytes => {
    const message = JSON.parse(bytes); if (message.type === 'desktop-registered') resolve(message.id);
  }));
  desktop.send(JSON.stringify({ type: 'desktop-register', rootIds: [b.id], sessionIds: [foreign.id], canReload: true }));
  const desktopId = await registration;
  const desktops = await client.callTool({ name: 'list_desktops', arguments: {} });
  assert.deepEqual(JSON.parse(desktops.content[0].text).desktops, []);
  const foreignReload = await client.callTool({ name: 'reload_desktop', arguments: { id: desktopId } });
  assert.equal(foreignReload.isError, true);
  desktop.terminate();
  await client.close();
  await writeFile(contextFile, JSON.stringify({ url: server.url, token: server.token, instance: 'different-instance', rootId: a.id }), { mode: 0o600 });
  const staleClient = new Client({ name: 'rengine-stale-test', version: '1.0.0' });
  const staleTransport = new StdioClientTransport({ command: process.execPath, args: [path.resolve('orchestrator/agents/mcp.mjs'), '--context', contextFile], stderr: 'pipe' });
  t.after(() => staleClient.close());
  await assert.rejects(staleClient.connect(staleTransport), /Connection closed/);
});
