import { bashPath } from '../server/sessions.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, realpath, stat, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { setTimeout as delay } from 'node:timers/promises';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { startServer } from '../server/main.mjs';
import { startRuntime } from '../runtime/supervisor.mjs';
import { launchDesktop, nativeBinary } from '../runtime/desktop.mjs';
import { nativeBridge, nativeClient } from './native-client.mjs';

const execute = promisify(execFile);
test('project windows retain one agent, isolated layouts, inspection and durable two-root reports', { timeout: 60000 }, async () => {
  const directory = await realpath(await mkdtemp(path.join(tmpdir(), 'rengine-project-windows-')));
  const clients = [], views = []; let host, runtime, originUI, controlUI;
  try {
    const originPath = path.join(directory, 'engine'), projectPath = path.join(directory, 'game $(literal)'), foreignPath = path.join(directory, 'foreign');
    for (const p of [originPath, projectPath, foreignPath]) await mkdir(p);
    await writeFile(path.join(projectPath, 'note.txt'), 'game disk text\n');
    const marker = path.join(originPath, 'invocations.txt'), fixture = path.join(originPath, 'agent.cjs');
    await writeFile(fixture, `require('node:fs').appendFileSync(${JSON.stringify(marker)}, 'once\\n'); process.stdin.setRawMode(true); console.log('ORIGINAL_AGENT_READY'); process.stdin.on('data', x => console.log('INPUT_' + x.toString('hex')));`);
    host = await startServer({ stateDir: path.join(directory, 'host') });
    const origin = await host.store.addRoot(originPath), project = await host.store.addRoot(projectPath), foreign = await host.store.addRoot(foreignPath);
    const agent = await host.sessions.terminal({ rootId: origin.id, command: process.execPath, args: [fixture] });
    host.sessions.items.get(agent.id).type = 'agent';
    originUI = await nativeClient(host, { root: origin.id, agent: agent.id });
    await originUI.until(s => s.tabs.some(t => t?.session === agent.id && t.text?.includes('ORIGINAL_AGENT_READY')));
    await delay(400); const originalLayout = structuredClone(host.store.state.layout);
    const runtimeDir = path.join(directory, 'runtime');
    runtime = await startRuntime({ host, directory: runtimeDir, inspectUI: true, onDesktop: child => child.once('spawn', () => views.push(nativeBridge(child))) });
    const connect = async root => {
      const context = path.join(directory, `${root.id}.json`);
      await writeFile(context, JSON.stringify({ url: host.url, token: host.token, instance: host.instance, rootId: root.id, runtimeDirectory: runtimeDir }));
      const client = new Client({ name: 'window-proof', version: '1' }); clients.push(client);
      await client.connect(new StdioClientTransport({ command: process.execPath, args: [path.resolve('orchestrator/agents/mcp.mjs'), '--context', context], stderr: 'pipe' }));
      const call = async (name, args = {}) => { const result = await client.callTool({ name, arguments: args }); assert.ok(!result.isError, JSON.stringify(result)); return result.structuredContent ?? JSON.parse(result.content[0].text); };
      return { client, call, context };
    };
    const source = await connect(origin), target = await connect(project), outsider = await connect(foreign);
    const opened = await source.call('open_project_window', { path: projectPath, agentId: agent.id }), windowId = opened.id;
    assert.equal(opened.originRootId, origin.id); assert.equal(opened.projectRootId, project.id);
    let gui = views.at(-1);
    await gui.until(s => s.tabs.some(t => t?.type === 1 && t.root === project.id) && s.tabs.some(t => t?.session === agent.id && t.root === origin.id && t.text?.includes('ORIGINAL_AGENT_READY')));
    assert.equal((await source.call('open_project_window', { path: projectPath, agentId: agent.id })).pid, opened.pid);
    await gui.control('tree-entry', 'note.txt');
    let state = await gui.until(s => s.tabs.some(t => t?.type === 2 && t.text === 'game disk text\n'));
    const editor = state.tabs.find(t => t?.type === 2); await gui.click(editor.rect[0] + 10, editor.rect[1] + 10);
    await gui.command({ op: 'text', text: 'Retain this draft ' });
    await gui.until(s => s.tabs.some(t => t?.dirty)); await delay(400);
    assert.deepEqual(host.store.state.layout, originalLayout, 'project window never overwrites the original window layout');
    const inspect = await source.call('project_window_action', { windowId, action: 'inspect', screenshot: true });
    const projectLayout = inspect.state.layout; assert.equal(inspect.pid, opened.pid); assert.ok(inspect.state.tabs.some(t => t?.dirty)); assert.equal(inspect.state.state, undefined);
    assert.ok((await stat(inspect.snapshot)).size > 1000);
    await mkdir('.cache/evidence', { recursive: true }); await writeFile('.cache/evidence/project-window.bmp', await readFile(inspect.snapshot));
    assert.equal((await source.call('project_window_action', { windowId, action: 'focus' })).requested, true);
    assert.equal((await outsider.client.callTool({ name: 'project_window_action', arguments: { windowId, action: 'inspect' } })).isError, true);
    const report = { windowId, key: 'fixture-issue', kind: 'issue', summary: 'Window integration finding', detail: 'Report text is data: $(do-not-run)', evidence: ['local:fixture'] };
    const sent = await target.call('report_integration', report);
    assert.equal((await target.call('report_integration', report)).reused, true);
    assert.equal((await target.client.callTool({ name: 'report_integration', arguments: { ...report, summary: 'Changed' } })).isError, true);
    assert.equal((await outsider.client.callTool({ name: 'report_integration', arguments: report })).isError, true);
    const inbox = await source.call('integration_inbox'); assert.equal(inbox.reports[0].sequence, sent.report.sequence);
    await source.call('report_integration', { ...report, key: 'response', kind: 'status', summary: 'rEngine fix ready' });
    assert.equal((await target.call('integration_inbox')).reports[0].summary, 'rEngine fix ready');
    await source.call('report_integration', { ...report, fromProject: true, key: 'same-agent', summary: 'Same agent finding from game window' });
    const update = await source.call('update_workspace', { layers: ['workspace', 'connector'] });
    let job;
    for (let i = 0; i < 100; i++) { job = (await source.call('update_status')).jobs.find(x => x.id === update.jobId); if (job?.finishedAt) break; await delay(50); }
    assert.equal(job.status, 'succeeded');
    assert.equal((await source.call('integration_inbox', { after: inbox.cursor })).reports[0].summary, 'Same agent finding from game window');
    assert.equal((await source.call('project_window_action', { windowId, action: 'close' })).sessionsRetained, true);
    assert.equal(host.sessions.snapshot(agent.id).pid, agent.pid); assert.equal(host.sessions.snapshot(agent.id).state, 'running');
    assert.equal((await source.call('list_project_windows')).windows[0].status, 'closed');
    await source.call('project_window_action', { windowId, action: 'reopen' }); gui = views.at(-1);
    const reopened = await gui.until(s => s.tabs.some(t => t?.dirty && t.text.includes('Retain this draft')));
    assert.deepEqual(reopened.layout, projectLayout, 'selected editor and pane layout survive close/reopen');
    assert.equal(await readFile(path.join(projectPath, 'note.txt'), 'utf8'), 'game disk text\n');
    const cli = await execute(bashPath(), ['orchestrator/actions/project-window.sh', '--context', source.context, '--project', projectPath, '--agent', agent.id]);
    assert.match(cli.stdout, new RegExp(windowId)); assert.match(cli.stderr, /Completed 3 stages/);
    assert.equal((await source.call('list_project_windows')).windows.length, 1);
    const scriptPath = path.join(originPath, 'choice.sh');
    await writeFile(scriptPath, 'printf "CHOOSE:%s\\n" "$1"; IFS= read -r choice; printf "SELECTED:%s\\n" "$choice"; IFS= read -r finish; printf "FLOW_DONE\\n"\n');
    const desktopId = (await source.call('list_desktops')).desktops.find(x => x.owner === windowId).id;
    const beforeScripts = host.sessions.items.size;
    const rejected = await source.client.callTool({ name: 'open_script', arguments: { path: '../foreign/no.sh', desktopId } });
    assert.equal(rejected.isError, true);
    await writeFile(path.join(foreignPath, 'outside.sh'), 'exit 0\n'); await symlink(path.join(foreignPath, 'outside.sh'), path.join(originPath, 'escape.sh'));
    assert.equal((await source.client.callTool({ name: 'open_script', arguments: { path: 'escape.sh', desktopId } })).isError, true);
    assert.equal((await outsider.client.callTool({ name: 'open_script', arguments: { path: 'outside.sh', desktopId } })).isError, true);
    assert.equal(host.sessions.items.size, beforeScripts);
    const flow = await source.call('open_script', { path: 'choice.sh', args: ['literal $(not-a-command)'], desktopId });
    assert.equal(flow.view.status, 'accepted');
    state = await gui.until(s => s.tabs.some(t => t?.session === flow.session.id && t.text?.includes('CHOOSE:literal $(not-a-command)')));
    const flowTab = state.tabs.findIndex(t => t?.session === flow.session.id);
    await gui.control('detach', '', flowTab);
    assert.equal(host.sessions.snapshot(flow.session.id).state, 'running');
    await source.call('show_session', { id: flow.session.id, desktopId });
    state = await gui.until(s => s.tabs.some(t => t?.session === flow.session.id && t.attached && t.rect[2] > 0));
    const box = state.tabs.find(t => t?.session === flow.session.id).rect; await gui.click(box[0] + 20, box[1] + 20);
    await gui.command({ op: 'text', text: 'choice one' }); await gui.key('Return');
    await gui.until(s => s.tabs.some(t => t?.session === flow.session.id && t.text?.includes('SELECTED:choice one')));
    assert.equal(host.sessions.snapshot(flow.session.id).pid, flow.session.pid);
    await gui.key('Return'); await gui.until(s => s.tabs.some(t => t?.session === flow.session.id && t.text?.includes('FLOW_DONE')));
    assert.equal(host.sessions.snapshot(agent.id).pid, agent.pid);
    await runtime.close(); runtime = await startRuntime({ host, directory: runtimeDir });
    assert.equal((await source.call('integration_inbox')).reports.length, 2, 'reports survive supervisor store reload too');
    assert.equal((await source.call('list_project_windows')).windows[0].id, windowId);
    controlUI = nativeBridge(launchDesktop(nativeBinary, runtime, { root: project.id, owner: 'control-fixture', view: 'control-view' }));
    assert.equal(await controlUI.command({ op: 'text', text: 'must not enter' }), 'Unsupported window control operation');
    assert.equal(await controlUI.command({ op: 'control-focus' }), true);
    assert.equal(await readFile(marker, 'utf8'), 'once\n');
    await controlUI.command({ op: 'control-close' });
    for (let i = 0; i < 80 && controlUI.child.exitCode === null; i++) await delay(50);
    assert.equal(controlUI.child.exitCode, 0);
  } finally {
    if (controlUI?.child.exitCode === null) controlUI.child.kill();
    for (const client of clients) await client.close();
    await runtime?.close(); await originUI?.close(); await host?.close(); await rm(directory, { recursive: true, force: true });
  }
});
