import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { setTimeout as delay } from 'node:timers/promises';
import { startServer } from '../server/main.mjs';
import { nativeClient } from './native-client.mjs';

test('native terminals scroll retained PTY history and return to the live prompt', { timeout: 45000 }, async () => {
  const directory = await mkdtemp(path.join(tmpdir(), 'rengine-terminal-scroll-'));
  let server, gui;
  try {
    const fixture = path.join(directory, 'history.cjs');
    await writeFile(fixture, `process.stdin.setRawMode(true);
for (let i = 0; i < 150; i++) process.stdout.write('\\x1b[32mHISTORY_' + String(i).padStart(3, '0') + ' café 世界\\x1b[0m\\r\\n');
process.stdin.on('data', data => {
  if (data.toString() === 'm') for (let i = 0; i < 12; i++) process.stdout.write('MORE_' + i + '\\r\\n');
  else if (data.toString() === 'a') { process.stdout.write('\\x1b[?1049h\\x1b[2J\\x1b[H'); for (let i = 0; i < 80; i++) process.stdout.write('ALT_' + i + '\\r\\n'); }
  else if (data.toString() === 'n') process.stdout.write('\\x1b[?1049l');
  else if (data.toString() === 'R' && process.env.RENGINE_TERMINAL_REPLAY) process.stdout.write(require('node:fs').readFileSync(process.env.RENGINE_TERMINAL_REPLAY) + '\\r\\nREPLAY_READY\\r\\n');
  else process.stdout.write('INPUT_' + data.toString('hex') + '\\r\\n');
});
`);
    server = await startServer({ stateDir: path.join(directory, 'state') });
    const root = await server.store.addRoot(directory);
    const first = await server.sessions.terminal({ rootId: root.id, command: process.execPath, args: [fixture] });
    gui = await nativeClient(server, { root: root.id, terminal: first.id });
    let state = await gui.until(s => s.tabs.some(t => t?.session === first.id && t.text?.includes('HISTORY_149')));
    let index = state.tabs.findIndex(t => t?.session === first.id), tab = state.tabs[index];
    await gui.click(tab.rect[0] + 15, tab.rect[1] + 15);
    await gui.command({ op: 'wheel', y: 12 });
    state = await gui.until(s => s.tabs[index]?.text?.includes('HISTORY_100'), 'older PTY rows after native wheel');
    assert.ok(!state.tabs[index].text.includes('HISTORY_149'));
    await gui.key('Home', 3);
    state = await gui.until(s => s.tabs[index]?.text?.includes('HISTORY_000'), 'oldest retained row');
    assert.match(state.tabs[index].text, /café 世界/);
    const reading = state.tabs[index].text, history = state.tabs[index].historyLines;
    server.sessions.input(first.id, 'm');
    state = await gui.until(s => s.tabs[index]?.historyLines >= history + 12, 'new PTY output while reading history');
    assert.equal(state.tabs[index].text, reading);
    await mkdir('.cache/evidence', { recursive: true });
    await gui.command({ op: 'snapshot', path: path.resolve('.cache/evidence/native-terminal-scroll.bmp') });
    await gui.command({ op: 'text', text: 'x' });
    await gui.until(s => s.tabs[index]?.text?.includes('INPUT_78'), 'typing returns to live PTY');
    await gui.key('PageUp', 3);
    await gui.until(s => !s.tabs[index]?.text?.includes('INPUT_78'), 'Shift+PageUp history');
    await gui.key('End', 3);
    await gui.until(s => s.tabs[index]?.text?.includes('INPUT_78'), 'Shift+End live prompt');
    state = await gui.command({ op: 'state' });
    const primaryLines = state.tabs[index].historyLines;
    await gui.command({ op: 'text', text: 'a' });
    await gui.until(s => s.tabs[index]?.text?.includes('ALT_79'), 'real alternate screen');
    await gui.command({ op: 'wheel', y: 100 }); await delay(80);
    state = await gui.command({ op: 'state' });
    assert.equal(state.tabs[index].scrollOffset, 0); assert.equal(state.tabs[index].historyLines, primaryLines);
    await gui.command({ op: 'text', text: 'n' });
    await gui.until(s => s.tabs[index]?.text?.includes('INPUT_78'), 'primary screen restored');
    await gui.command({ op: 'resize', width: 1050, height: 480 }); await delay(150);
    await gui.command({ op: 'resize', width: 1280, height: 800 }); await delay(150);
    await gui.key('Home', 3);
    await gui.until(s => s.tabs[index]?.text?.includes('HISTORY_000 café 世界'), 'history survives resize');
    await gui.key('End', 3);
    await gui.control('toolbar', 'Shell');
    state = await gui.until(s => s.tabs.filter(t => t?.type === 3).length === 2, 'second shell');
    const secondIndex = state.tabs.findIndex(t => t?.type === 3 && t.session !== first.id);
    const second = server.sessions.snapshot(state.tabs[secondIndex].session);
    await gui.control('tab', '', index); state = await gui.command({ op: 'state' }); tab = state.tabs[index];
    await gui.command({ op: 'button', x: tab.header[0] + 20, y: tab.header[1] + 12, down: true });
    await gui.command({ op: 'motion', x: 100, y: 420 });
    await gui.command({ op: 'button', x: 100, y: 420, down: false });
    await gui.until(s => s.tabs[index]?.rect[0] < 100 && s.tabs[index].rect[2] > 0, 'terminal moved into left pane');
    await gui.control('tab', '', secondIndex); state = await gui.command({ op: 'state' });
    const other = state.tabs[secondIndex];
    await gui.click(other.rect[0] + 15, other.rect[1] + 15);
    tab = state.tabs[index]; await gui.command({ op: 'motion', x: tab.rect[0] + 15, y: tab.rect[1] + 15 });
    await gui.command({ op: 'wheel', y: 12 });
    state = await gui.until(s => s.tabs[index]?.scrollOffset > 0, 'hovered terminal scrolls without keyboard focus');
    assert.equal(state.focus, secondIndex); assert.equal(state.tabs[secondIndex].scrollOffset, 0);
    await gui.command({ op: 'text', text: "printf 'FOCUS_%s\\n' RETAINED" }); await gui.key('Return');
    await gui.until(s => s.tabs[secondIndex]?.text?.includes('FOCUS_RETAINED'), 'keyboard stays with other shell');
    await gui.close(); gui = null;
    assert.equal(server.sessions.snapshot(first.id).pid, first.pid);
    assert.equal(server.sessions.snapshot(first.id).state, 'running');
    gui = await nativeClient(server, { root: root.id, terminal: first.id });
    state = await gui.until(s => s.tabs.some(t => t?.session === first.id && t.text?.includes('INPUT_78')));
    index = state.tabs.findIndex(t => t?.session === first.id); tab = state.tabs[index];
    await gui.click(tab.rect[0] + 15, tab.rect[1] + 15); await gui.key('Home', 3);
    await gui.until(s => s.tabs[index]?.text?.includes('HISTORY_000'), 'history rebuilt from same retained PTY');
    if (process.env.RENGINE_TERMINAL_REPLAY) {
      await gui.command({ op: 'text', text: 'R' });
      state = await gui.until(s => s.tabs[index]?.text?.includes('REPLAY_READY'), 'recorded CLI bytes rendered');
      const liveText = state.tabs[index].text;
      await gui.command({ op: 'wheel', y: 30 });
      state = await gui.until(s => s.tabs[index]?.scrollOffset > 0 && s.tabs[index].text !== liveText, 'recorded CLI history scrolls');
      assert.ok(!state.tabs[index].text.includes('REPLAY_READY'));
      await gui.command({ op: 'snapshot', path: path.resolve('.cache/evidence/native-terminal-scroll-replay.bmp') });
      await gui.key('End', 3);
      await gui.until(s => s.tabs[index]?.text?.includes('REPLAY_READY'), 'recorded CLI returns to live screen');
    }
    assert.equal(server.sessions.snapshot(second.id).pid, second.pid);
    assert.equal(server.sessions.list().length, 2);
  } finally { await gui?.close(); await server?.close(); await rm(directory, { recursive: true, force: true }); }
});
