/* Generated by `python3 tools/design.py generate` from the product declaration in
 * orchestrator/native/theme.json. Edit the declaration, never this file (charter D41, spec 108). */
export const PRODUCT_NAME = "rEdit";
export const PRODUCT_FAMILY = "Red";
