/* F146 (spec 129, charter D41/D57): tools/design.py emits a Rust target beside the .mjs and .h
 * outputs, so no Rust source ever hand-writes the product name or the theme tokens — the values
 * D41 made a data edit. The generated module is red/red-core/src/theme.rs; the name guard scans
 * .rs sources exactly as it scans C, JS and Python.
 *
 * The compile side of the contract — red-core and red-link build against these constants — is
 * gated by the rust_red_core/rust_red_link CTest targets, not re-run here; what this file pins is
 * that the generated module carries the declaration, that both crates read it, and that the guard
 * goes red for its own reason on a Rust decoy.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const PYTHON = process.platform === 'win32' ? 'python' : 'python3';
const run = promisify(execFile);
const THEME_RS = path.join(ROOT, 'red/red-core/src/theme.rs');

test('the generated Rust module carries the declaration, not a copy of it', async () => {
  const declared = JSON.parse(await readFile(path.join(ROOT, 'orchestrator/native/theme.json'), 'utf8'));
  const rust = await readFile(THEME_RS, 'utf8');
  assert.match(rust, /Generated by `python3 tools\/design\.py generate`/,
    'the module is marked generated; a hand-written lookalike is what check rejects');

  const stringConst = key => new RegExp(`pub const ${key}: &str = "(.*)";`).exec(rust)?.[1];
  assert.equal(stringConst('PRODUCT_NAME'), declared.product.name, 'the name is generated from theme.json');
  assert.equal(stringConst('PRODUCT_FAMILY'), declared.product.family);

  const intConst = key => Number(new RegExp(`pub const ${key}: i32 = (-?\\d+);`).exec(rust)?.[1]);
  assert.equal(intConst('THEME_FONT_SIZE'), declared.typography.size);
  assert.equal(intConst('THEME_LINE_HEIGHT'), declared.typography['line-height']);
  for (const [group, values] of Object.entries(declared.metrics))
    for (const [key, value] of Object.entries(values)) {
      const constant = `METRIC_${group}_${key}`.toUpperCase().replaceAll('-', '_');
      assert.equal(intConst(constant), value, `metric ${group}.${key}`);
    }

  // The preset tables: one entry per preset in design/tokens.css plus default, one row per bound
  // colour — the same data theme.c carries, so a Rust microui host never restates a token.
  const presets = (await readFile(path.join(ROOT, 'design/tokens.css'), 'utf8'))
    .match(/\[data-theme="/g).length + 1;
  const count = kind => Number(new RegExp(`pub const ${kind}: usize = (\\d+);`).exec(rust)?.[1]);
  assert.equal(count('PRESET_COUNT'), presets, 'every tokens.css preset is generated');
  assert.equal(count('COLOR_COUNT'), Object.keys(declared.colors).length, 'every bound colour is generated');
  assert.match(rust, /pub const THEME_PRESETS: \[\[\[u8; 4\]; COLOR_COUNT\]; PRESET_COUNT\]/);
});

test('both crates read the generated constants rather than restating them', async () => {
  const lib = await readFile(path.join(ROOT, 'red/red-core/src/lib.rs'), 'utf8');
  assert.match(lib, /pub mod theme;/, 'red-core exposes the generated module');
  const main = await readFile(path.join(ROOT, 'red/red-link/src/main.rs'), 'utf8');
  assert.match(main, /red_core::theme::PRODUCT_NAME/, 'red-link speaks the generated product name');
});

test('the name guard covers Rust sources and goes red for its own reason', async () => {
  const clean = await run(PYTHON, ['tools/design.py', 'product'], { cwd: ROOT }).catch(error => error);
  const report = JSON.parse(clean.stdout);
  assert.deepEqual(report.problems, [], 'a hand-written product name is in the shipping tree');
  assert.ok(report.generated.includes('red/red-core/src/theme.rs'),
    'the generated Rust module is the one .rs file allowed to carry the name');

  // The decoy is written outside the tree because other agents are working in it; `product PATH`
  // scans what it is pointed at. The comment is prose and must not fire; the string and the enum
  // variant are code and must — a name outside a string is exactly what a strings-only guard misses.
  const directory = await mkdtemp(path.join(tmpdir(), 'rengine-rust-decoy-'));
  const decoy = path.join(directory, 'decoy.rs');
  await writeFile(decoy, [
    `// A comment naming ${report.family} is prose; a file has to be able to say what it is.`,
    `const NAME: &str = "${report.name}";`,
    `enum Product { ${report.family} }`,
    ''].join('\n'));
  try {
    await assert.rejects(() => run(PYTHON, ['tools/design.py', 'product', decoy], { cwd: ROOT }),
      error => {
        const found = JSON.parse(error.stdout).problems;
        assert.equal(found.length, 2, `the string and the variant, not the comment: ${found.join('; ')}`);
        assert.match(found[0], /decoy\.rs:2: hard-coded product name/);
        assert.match(found[1], /decoy\.rs:3: hard-coded product name/);
        assert.match(found[0], /red_core::theme::PRODUCT_NAME/, 'the hint names the Rust constant');
        return true;
      });
  } finally { await rm(directory, { recursive: true, force: true }); }
});
