/* Generated by `python3 tools/design.py generate` from design/tokens.css and the bindings in
 * orchestrator/native/theme.json. Edit the tokens or the bindings, never this file. */
#ifndef RENGINE_THEME_H
#define RENGINE_THEME_H
#include <stdint.h>
#include "microui.h"
#define RE_THEME_FONT_SIZE 16
#define RE_THEME_LINE_HEIGHT 20
#define RE_METRIC_MICROUI_PADDING 5
#define RE_METRIC_MICROUI_SPACING 4
#define RE_METRIC_MICROUI_INDENT 24
#define RE_METRIC_MICROUI_TITLE_HEIGHT 24
#define RE_METRIC_MICROUI_SCROLLBAR_SIZE 12
#define RE_METRIC_MICROUI_THUMB_SIZE 8
#define RE_METRIC_MICROUI_CONTROL_WIDTH 68
#define RE_METRIC_WINDOW_WIDTH 1280
#define RE_METRIC_WINDOW_HEIGHT 800
#define RE_METRIC_WINDOW_MIN_WIDTH 1050
#define RE_METRIC_WINDOW_MIN_HEIGHT 480
#define RE_METRIC_TOOLBAR_HEIGHT 36
#define RE_METRIC_TOOLBAR_ROW_HEIGHT 26
#define RE_METRIC_TOOLBAR_BRAND_WIDTH 78
#define RE_METRIC_TOOLBAR_VIEW_WIDTH 75
#define RE_METRIC_TOOLBAR_MANAGE_WIDTH 80
#define RE_METRIC_TOOLBAR_SESSIONS_WIDTH 95
#define RE_METRIC_TOOLBAR_SPLIT_VERTICAL_WIDTH 120
#define RE_METRIC_TOOLBAR_SPLIT_HORIZONTAL_WIDTH 125
#define RE_METRIC_TOOLBAR_MERGE_WIDTH 95
#define RE_METRIC_TOOLBAR_ROOT_WIDTH 170
#define RE_METRIC_TOOLBAR_PATH_RIGHT 475
#define RE_METRIC_TOOLBAR_ADD_WIDTH 95
#define RE_METRIC_TOOLBAR_AGENT_LABEL_WIDTH 70
#define RE_METRIC_TOOLBAR_DASHBOARD_WIDTH 100
#define RE_METRIC_TOOLBAR_AGENT_WIDTH 120
#define RE_METRIC_WORKSPACE_TOP 36
#define RE_METRIC_WORKSPACE_STATUS_HEIGHT 22
#define RE_METRIC_WORKSPACE_STATUS_INSET 8
#define RE_METRIC_WORKSPACE_STATUS_TEXT_TOP 2
#define RE_METRIC_WORKSPACE_DIVIDER 6
#define RE_METRIC_WORKSPACE_PANE_MINIMUM 80
#define RE_METRIC_WORKSPACE_TREE_PERCENT 23
#define RE_METRIC_PANE_HEADER_HEIGHT 28
#define RE_METRIC_PANE_CONTENT_TOP 29
#define RE_METRIC_PANE_ROOT_ROW_HEIGHT 22
#define RE_METRIC_PANE_EMPTY_ROW_HEIGHT 24
#define RE_METRIC_TAB_WIDTH 170
#define RE_METRIC_TAB_HEIGHT 26
#define RE_METRIC_TAB_TOP 2
#define RE_METRIC_TAB_INSET 5
#define RE_METRIC_TAB_GAP 2
#define RE_METRIC_TAB_CLOSE_WIDTH 24
#define RE_METRIC_TAB_NAV_WIDTH 24
#define RE_METRIC_TAB_TITLE_CHARACTERS 11
#define RE_METRIC_TREE_ROW_HEIGHT 24
#define RE_METRIC_TREE_UP_WIDTH 55
#define RE_METRIC_TREE_ROW_CAP 1200
#define RE_METRIC_SESSIONS_ROW_HEIGHT 26
#define RE_METRIC_SESSIONS_ACTIONS_WIDTH 155
#define RE_METRIC_SESSIONS_ATTACH_WIDTH 80
#define RE_METRIC_SESSIONS_HEADING_HEIGHT 24
#define RE_METRIC_SESSIONS_STATE_WIDTH 150
#define RE_METRIC_SESSIONS_TOKEN_WIDTH 84
#define RE_METRIC_EDITOR_TOOLBAR_HEIGHT 26
#define RE_METRIC_EDITOR_SAVE_WIDTH 65
#define RE_METRIC_EDITOR_DISCARD_WIDTH 80
#define RE_METRIC_EDITOR_MODE_WIDTH 130
#define RE_METRIC_EDITOR_INSET 6
#define RE_METRIC_EDITOR_TOP 59
#define RE_METRIC_EDITOR_BOTTOM 85
#define RE_METRIC_EDITOR_CARET_WIDTH 2
#define RE_METRIC_EDITOR_DIAGNOSTIC_HEIGHT 2
#define RE_METRIC_EDITOR_ERROR_HEIGHT 23
#define RE_METRIC_EDITOR_ERROR_INSET 2
#define RE_METRIC_EDITOR_TAB_CELLS 4
#define RE_METRIC_TERMINAL_INSET 6
#define RE_METRIC_TERMINAL_TOP 28
#define RE_METRIC_TERMINAL_BOTTOM 34
#define RE_METRIC_GAME_ROW_HEIGHT 26
#define RE_METRIC_GAME_CAPTURE_WIDTH 210
#define RE_METRIC_GAME_INSET 6
#define RE_METRIC_GAME_TOP 59
#define RE_METRIC_GAME_BOTTOM 65
#define RE_METRIC_SCROLLBAR_SIZE 10
#define RE_METRIC_SCROLLBAR_THUMB_MIN 20
#define RE_METRIC_SCROLLBAR_THUMB_INSET 2
#define RE_METRIC_FORMAT_TOOLBAR_HEIGHT 26
#define RE_METRIC_FORMAT_MODE_WIDTH 75
#define RE_METRIC_FORMAT_ACTION_WIDTH 90
#define RE_METRIC_FORMAT_PAGE_WIDTH 70
#define RE_METRIC_FORMAT_ROW_ADVANCE 30
#define RE_METRIC_FORMAT_ROW_HEIGHT 22
#define RE_METRIC_FORMAT_SIZE_WIDTH 110
#define RE_METRIC_FORMAT_ENTRY_PERCENT 50
#define RE_METRIC_FORMAT_HEADER_HEIGHT 22
#define RE_METRIC_FORMAT_TREE_DEPTH 10
#define RE_METRIC_DASHBOARD_HEADING_HEIGHT 26
#define RE_METRIC_DASHBOARD_ROW_HEIGHT 26
#define RE_METRIC_DASHBOARD_DESCRIPTION_HEIGHT 20
#define RE_METRIC_DASHBOARD_REFRESH_WIDTH 90
#define RE_METRIC_DASHBOARD_ARTIFACT_WIDTH 260
#define RE_METRIC_DASHBOARD_NOTE_HEIGHT 24
#define RE_METRIC_DEVICES_HEADING_HEIGHT 26
#define RE_METRIC_DEVICES_ROW_HEIGHT 26
#define RE_METRIC_DEVICES_REASON_HEIGHT 20
#define RE_METRIC_DEVICES_REFRESH_WIDTH 90
#define RE_METRIC_DEVICES_STATUS_WIDTH 120
#define RE_METRIC_DEVICES_KIND_WIDTH 110
#define RE_METRIC_DEVICES_NOTE_HEIGHT 24
#define RE_METRIC_DESIGN_FOCUS_WIDTH 2
#define RE_METRIC_DESIGN_TRANSITION_MS 90
#define RE_METRIC_DESIGN_CONTROL_HEIGHT 24
#define RE_METRIC_DESIGN_CONTROL_PAD 10
#define RE_METRIC_DESIGN_FIELD_PAD 8
#define RE_METRIC_DESIGN_ICON_GAP 6
#define RE_METRIC_DESIGN_ICON_BUTTON 22
#define RE_METRIC_DESIGN_CHECKBOX_BOX 14
#define RE_METRIC_DESIGN_BRAND_MARK 16
#define RE_METRIC_DESIGN_BRAND_RADIUS 4
#define RE_METRIC_DESIGN_TOOLBAR_PAD 10
#define RE_METRIC_DESIGN_SEPARATOR_HEIGHT 16
#define RE_METRIC_DESIGN_GROUP_MARKER 2
#define RE_METRIC_DESIGN_PLACEHOLDER_ALPHA 60
#define RE_METRIC_DESIGN_EDITOR_GUTTER 44
#define RE_METRIC_SETTINGS_WIDTH 280
#define RE_METRIC_SETTINGS_LABEL_WIDTH 84
#define RE_METRIC_RECORDING_TOGGLE_WIDTH 96
#define RE_METRIC_RECORDING_COMMIT_WIDTH 168
#define RE_METRIC_TRACKER_HEADING_HEIGHT 26
#define RE_METRIC_TRACKER_ROW_HEIGHT 24
#define RE_METRIC_TRACKER_NOTE_HEIGHT 24
#define RE_METRIC_TRACKER_REFRESH_WIDTH 90
#define RE_METRIC_TRACKER_KEY_WIDTH 70
#define RE_METRIC_TRACKER_STATE_WIDTH 110
#define RE_METRIC_TOKEN_SEGMENT_PAD 10
#define RE_METRIC_TOKEN_POPOVER_WIDTH 300
#define RE_METRIC_TOKEN_LABEL_WIDTH 96
#define RE_METRIC_TOKEN_HEADING_HEIGHT 26
#define RE_METRIC_TOKEN_ROW_HEIGHT 22
#define RE_METRIC_TOKEN_ACTION_HEIGHT 24
#define RE_METRIC_TOKEN_ACTION_WIDTH 132
#define RE_METRIC_DESIGN_GAP 4
#define RE_METRIC_DESIGN_GAP_LG 8
#define RE_METRIC_DESIGN_LEADING 16
#define RE_METRIC_DESIGN_LEADING_LG 18
#define RE_METRIC_DESIGN_LEADING_SM 14
#define RE_METRIC_DESIGN_MONO_LEADING 19
#define RE_METRIC_DESIGN_MONO_SIZE 13
#define RE_METRIC_DESIGN_PAD 8
#define RE_METRIC_DESIGN_PANE_DIVIDER_SIZE 4
#define RE_METRIC_DESIGN_RADIUS 3
#define RE_METRIC_DESIGN_RADIUS_LG 6
#define RE_METRIC_DESIGN_ROW 22
#define RE_METRIC_DESIGN_ROW_LG 26
#define RE_METRIC_DESIGN_SCROLL_INSET 2
#define RE_METRIC_DESIGN_SCROLL_SIZE 10
#define RE_METRIC_DESIGN_SIZE 12
#define RE_METRIC_DESIGN_SIZE_LG 13
#define RE_METRIC_DESIGN_SIZE_SM 11
#define RE_METRIC_DESIGN_STATUS_HEIGHT 22
#define RE_METRIC_DESIGN_TABS_HEIGHT 28
#define RE_METRIC_DESIGN_TOOLBAR_HEIGHT 36
#define RE_METRIC_DESIGN_TREE_INDENT 14
#define RE_METRIC_DESIGN_TREE_ROW 22
typedef struct {
  mu_Color canvas;
  mu_Color surface;
  mu_Color surface_raised;
  mu_Color surface_sunken;
  mu_Color control;
  mu_Color control_hover;
  mu_Color control_active;
  mu_Color field;
  mu_Color field_hover;
  mu_Color field_active;
  mu_Color border;
  mu_Color border_soft;
  mu_Color highlight;
  mu_Color text;
  mu_Color text_strong;
  mu_Color text_muted;
  mu_Color text_faint;
  mu_Color text_indicator;
  mu_Color text_on_accent;
  mu_Color accent;
  mu_Color accent_hover;
  mu_Color focus;
  mu_Color title_bg;
  mu_Color title_text;
  mu_Color panel_bg;
  mu_Color divider;
  mu_Color divider_hover;
  mu_Color selection;
  mu_Color caret;
  mu_Color terminal_cursor;
  mu_Color indicator;
  mu_Color scroll_track;
  mu_Color scroll_thumb;
  mu_Color scroll_thumb_active;
  mu_Color list_scroll_track;
  mu_Color list_scroll_thumb;
  mu_Color game_backdrop;
  mu_Color toolbar_bg;
  mu_Color toolbar_fg;
  mu_Color tabs_bg;
  mu_Color tab_fg;
  mu_Color tab_active_bg;
  mu_Color tab_active_fg;
  mu_Color tab_marker;
  mu_Color tree_bg;
  mu_Color tree_fg;
  mu_Color tree_icon;
  mu_Color tree_selected_bg;
  mu_Color tree_selected_fg;
  mu_Color editor_bg;
  mu_Color editor_fg;
  mu_Color editor_gutter_fg;
  mu_Color editor_line_bg;
  mu_Color editor_selection;
  mu_Color terminal_bg;
  mu_Color terminal_fg;
  mu_Color status_bg;
  mu_Color status_fg;
  mu_Color status_accent_bg;
  mu_Color status_accent_fg;
  mu_Color ok;
  mu_Color warn;
  mu_Color err;
  mu_Color info;
  mu_Color editor_gutter_bg;
} ReTheme;
enum { RE_PRESET_DEFAULT = 0, RE_PRESET_TEAL = 1, RE_PRESET_LIGHT = 2, RE_PRESET_COUNT = 3 };
extern ReTheme re_theme;                                   /* the live theme; presets assign it whole */
extern int re_theme_preset;                                /* index of the live preset, for tables keyed by it */
extern const ReTheme re_theme_presets[RE_PRESET_COUNT];
extern const char *const re_theme_preset_names[RE_PRESET_COUNT];
int re_theme_select(const char *name);                     /* preset index, or -1 when unknown */
void re_theme_apply(mu_Style *style);                      /* pushes the live theme into microui's style */

/* The accent hue is the one token a person can move at runtime (spec 080). Each preset lists the
 * colours that follow it with the oklch lightness, chroma and alpha to rebuild them at a new hue. */
typedef struct { uint16_t index; float lightness, chroma; uint8_t alpha; } ReAccentSlot;
#define RE_THEME_COLOR_COUNT 65
extern const ReAccentSlot *const re_theme_accent_slots[RE_PRESET_COUNT];
extern const int re_theme_accent_counts[RE_PRESET_COUNT];
extern const float re_theme_accent_hues[RE_PRESET_COUNT];   /* each preset's own hue, in degrees */
float re_theme_hue(void);                                  /* the live accent hue */
void re_theme_hue_set(float hue);                          /* re-tints every accent-derived colour */
mu_Color re_theme_swatch(float hue);                       /* --re-accent at a hue, for the slider track */
mu_Color re_theme_from_oklch(float lightness, float chroma, float hue, unsigned char alpha);

/* The token graph, one entry per token per preset, values left unexpanded so a theme file can
 * override a token in any of the three layers and everything below it follows (charter D34). */
typedef struct { const char *name, *value; } ReToken;
extern const ReToken *const re_theme_tokens[RE_PRESET_COUNT];
extern const int re_theme_token_counts[RE_PRESET_COUNT];
extern const char *const re_theme_field_tokens[RE_THEME_COLOR_COUNT];  /* the token each colour binds */
#define RE_COLOR_CANVAS re_theme.canvas
#define RE_COLOR_SURFACE re_theme.surface
#define RE_COLOR_SURFACE_RAISED re_theme.surface_raised
#define RE_COLOR_SURFACE_SUNKEN re_theme.surface_sunken
#define RE_COLOR_CONTROL re_theme.control
#define RE_COLOR_CONTROL_HOVER re_theme.control_hover
#define RE_COLOR_CONTROL_ACTIVE re_theme.control_active
#define RE_COLOR_FIELD re_theme.field
#define RE_COLOR_FIELD_HOVER re_theme.field_hover
#define RE_COLOR_FIELD_ACTIVE re_theme.field_active
#define RE_COLOR_BORDER re_theme.border
#define RE_COLOR_BORDER_SOFT re_theme.border_soft
#define RE_COLOR_HIGHLIGHT re_theme.highlight
#define RE_COLOR_TEXT re_theme.text
#define RE_COLOR_TEXT_STRONG re_theme.text_strong
#define RE_COLOR_TEXT_MUTED re_theme.text_muted
#define RE_COLOR_TEXT_FAINT re_theme.text_faint
#define RE_COLOR_TEXT_INDICATOR re_theme.text_indicator
#define RE_COLOR_TEXT_ON_ACCENT re_theme.text_on_accent
#define RE_COLOR_ACCENT re_theme.accent
#define RE_COLOR_ACCENT_HOVER re_theme.accent_hover
#define RE_COLOR_FOCUS re_theme.focus
#define RE_COLOR_TITLE_BG re_theme.title_bg
#define RE_COLOR_TITLE_TEXT re_theme.title_text
#define RE_COLOR_PANEL_BG re_theme.panel_bg
#define RE_COLOR_DIVIDER re_theme.divider
#define RE_COLOR_DIVIDER_HOVER re_theme.divider_hover
#define RE_COLOR_SELECTION re_theme.selection
#define RE_COLOR_CARET re_theme.caret
#define RE_COLOR_TERMINAL_CURSOR re_theme.terminal_cursor
#define RE_COLOR_INDICATOR re_theme.indicator
#define RE_COLOR_SCROLL_TRACK re_theme.scroll_track
#define RE_COLOR_SCROLL_THUMB re_theme.scroll_thumb
#define RE_COLOR_SCROLL_THUMB_ACTIVE re_theme.scroll_thumb_active
#define RE_COLOR_LIST_SCROLL_TRACK re_theme.list_scroll_track
#define RE_COLOR_LIST_SCROLL_THUMB re_theme.list_scroll_thumb
#define RE_COLOR_GAME_BACKDROP re_theme.game_backdrop
#define RE_COLOR_TOOLBAR_BG re_theme.toolbar_bg
#define RE_COLOR_TOOLBAR_FG re_theme.toolbar_fg
#define RE_COLOR_TABS_BG re_theme.tabs_bg
#define RE_COLOR_TAB_FG re_theme.tab_fg
#define RE_COLOR_TAB_ACTIVE_BG re_theme.tab_active_bg
#define RE_COLOR_TAB_ACTIVE_FG re_theme.tab_active_fg
#define RE_COLOR_TAB_MARKER re_theme.tab_marker
#define RE_COLOR_TREE_BG re_theme.tree_bg
#define RE_COLOR_TREE_FG re_theme.tree_fg
#define RE_COLOR_TREE_ICON re_theme.tree_icon
#define RE_COLOR_TREE_SELECTED_BG re_theme.tree_selected_bg
#define RE_COLOR_TREE_SELECTED_FG re_theme.tree_selected_fg
#define RE_COLOR_EDITOR_BG re_theme.editor_bg
#define RE_COLOR_EDITOR_FG re_theme.editor_fg
#define RE_COLOR_EDITOR_GUTTER_FG re_theme.editor_gutter_fg
#define RE_COLOR_EDITOR_LINE_BG re_theme.editor_line_bg
#define RE_COLOR_EDITOR_SELECTION re_theme.editor_selection
#define RE_COLOR_TERMINAL_BG re_theme.terminal_bg
#define RE_COLOR_TERMINAL_FG re_theme.terminal_fg
#define RE_COLOR_STATUS_BG re_theme.status_bg
#define RE_COLOR_STATUS_FG re_theme.status_fg
#define RE_COLOR_STATUS_ACCENT_BG re_theme.status_accent_bg
#define RE_COLOR_STATUS_ACCENT_FG re_theme.status_accent_fg
#define RE_COLOR_OK re_theme.ok
#define RE_COLOR_WARN re_theme.warn
#define RE_COLOR_ERR re_theme.err
#define RE_COLOR_INFO re_theme.info
#define RE_COLOR_EDITOR_GUTTER_BG re_theme.editor_gutter_bg
#endif
