"""The Rust target of tools/design.py (F146, spec 129; charter D41/D57).

design.py resolves the theme data; this module formats it as red/red-core/src/theme.rs, so no
Rust source hand-writes the product name or a theme token — the values D41 made a data edit.
Standard library only; the name guard in design.py treats this file like design.py itself: it
receives the names as data and must never spell them.
"""
import json

HEADER = ("//! Generated by `python3 tools/design.py generate` from design/tokens.css and the bindings in\n"
          "//! orchestrator/native/theme.json. Edit the tokens or the bindings, never this file\n"
          "//! (charter D41, spec 108; the Rust target is spec 129, F146).")


def string(value):
    """A Rust string literal. JSON escaping is Rust escaping for the printable range, and theme
    data is printable; non-ASCII passes through as UTF-8, which a Rust source also is."""
    return json.dumps(value, ensure_ascii=False)


def constant(*parts):
    return "_".join(part.upper().replace("-", "_") for part in parts)


def theme_module(product, typography, metric_groups, design_metrics, fields, field_tokens,
                 presets, tables):
    out = [HEADER, "",
           "/// The product's own name, declared in theme.json (charter D41). Rust consumers read these",
           "/// rather than typing a second literal for the name guard to find.",
           "pub const PRODUCT_NAME: &str = %s;" % string(product["name"]),
           "pub const PRODUCT_FAMILY: &str = %s;" % string(product["family"]), "",
           "pub const THEME_FONT_SIZE: i32 = %d;" % typography["size"],
           "pub const THEME_LINE_HEIGHT: i32 = %d;" % typography["line-height"], ""]
    out.append("/// The literal metrics of theme.json, one constant per entry; the design token-metrics")
    out.append("/// follow, resolved against the default preset — the same values RE_METRIC_* carries.")
    for group, values in metric_groups.items():
        out += ["pub const %s: i32 = %d;" % (constant("metric", group, key), value)
                for key, value in values.items()]
    out += ["pub const %s: i32 = %d;" % (constant("metric", "design", key), value)
            for key, value in sorted(design_metrics.items())]
    out += ["",
            "/// The theme presets in declaration order; default is index 0, as on the C side (spec 076).",
            "pub const PRESET_COUNT: usize = %d;" % len(presets),
            "pub const PRESET_NAMES: [&str; PRESET_COUNT] = [%s];"
            % ", ".join(string(name) for name in presets), "",
            "/// The bound colours in declaration order, and the design token each binds (theme.json).",
            "pub const COLOR_COUNT: usize = %d;" % len(fields),
            "pub const COLOR_FIELDS: [&str; COLOR_COUNT] = [%s];"
            % ", ".join(string(name) for name in fields),
            "pub const COLOR_FIELD_TOKENS: [&str; COLOR_COUNT] = [%s];"
            % ", ".join(string(token) for token in field_tokens), "",
            "/// `[preset][colour]` as RGBA bytes — the same tables theme.c carries.",
            "pub const THEME_PRESETS: [[[u8; 4]; COLOR_COUNT]; PRESET_COUNT] = ["]
    for name in presets:
        out.append("    [ // %s" % name)
        out += ["        [%d, %d, %d, %d], // %s" % (tuple(tables[name][field]) + (field,))
                for field in fields]
        out.append("    ],")
    out.append("];")
    return "\n".join(out) + "\n"
