#!/usr/bin/env python3
"""Generate the symbol-rename headers that let three copies of the GPU seam share one binary.

The pack compiles exactly one backend per target (charter D14b/D51: Quest is the constrained
target and several seam calls are per-draw, so a game never pays an indirection). rEngine's
desktop keeps `--renderer` a runtime switch (spec 126 decision 3), which means one binary holding
three seams — and three definitions of `re_seam_draw`.

The answer is three copies of the same sources, each force-included (`-include` / `/FI`) with a
header that renames every symbol it defines: `re_seam_draw` becomes `re_opengl_seam_draw`,
`re_vulkan_seam_draw`, `re_metal_seam_draw`. The pack is not modified and a consumer outside this
repository never sees any of this — which is the property that keeps the pack a pack.

The rename list is DERIVED from the headers rather than maintained beside them, because a list that
is maintained by hand is a list that silently misses the next symbol someone adds. A missed symbol
does not fail the build: the linker takes the first definition and two renderers quietly share one
backend's function. `tools/seam_symbols.py` is the second half of that guard and checks the built
archives with `nm`, which catches anything this derivation gets wrong.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RENDER = ROOT / "orchestrator/native/render"
APIS = ("opengl", "vulkan", "metal")

# Every header that declares a symbol one of the three copies DEFINES. The pack's two public
# headers, its two private cross-translation-unit headers, and rEngine's own two — backend_seam.c
# and the host are compiled once per copy exactly like the pack's sources, so their entry points
# collide in precisely the same way.
HEADERS = [
    ROOT / "packs/gpu/include/rengine/gpu_seam.h",
    ROOT / "packs/gpu/include/rengine/gpu_device.h",
    ROOT / "packs/gpu/src/gpu_seam_vk_internal.h",
    ROOT / "packs/gpu/src/gpu_seam_spirv.h",
    RENDER / "backend_seam.h",
    RENDER / "seam_host.h",
]
# The families a copy defines. `re_spirv_` is the shared reflector, which Vulkan and Metal both
# compile; `re_backend_seam_` and `re_seam_host_` are rEngine's own halves of the same problem.
FAMILIES = ("re_seam_", "re_gpu_", "re_spirv_", "re_backend_seam_", "re_seam_host_")
DECLARATION = re.compile(r"\b((?:" + "|".join(FAMILIES) + r")[A-Za-z0-9_]*)\s*\(")


def symbols():
    """Every function name the copies define, in a stable order."""
    found = {}
    for header in HEADERS:
        if not header.exists():
            raise SystemExit("seam_prefix: missing header %s" % header.relative_to(ROOT))
        for line in header.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("*") or stripped.startswith("//"):
                continue  # prose in a comment block names these functions constantly
            for name in DECLARATION.findall(line):
                found.setdefault(name, header)
    return sorted(found)


def renamed(name, api):
    """`re_seam_draw` under `metal` becomes `re_metal_seam_draw`: the API goes where it can be read."""
    return "re_%s_%s" % (api, name[len("re_"):])


def header_text(api, names):
    lines = [
        "/* GENERATED by tools/seam_prefix.py -- do not edit. Regenerate with `python3 tools/seam_prefix.py generate`.",
        " *",
        " * Force-included into the %s copy of the seam, rEngine's draw-list backend and its host, so" % api,
        " * that copy defines and calls %s-prefixed symbols and three copies link into one binary" % ("re_%s_" % api),
        " * (spec 124, spec 126 decision 3). The pack's own sources are unmodified; this is applied",
        " * from the build with -include (/FI on MSVC).",
        " */",
        "#ifndef RENGINE_SEAM_PREFIX_%s_H" % api.upper(),
        "#define RENGINE_SEAM_PREFIX_%s_H" % api.upper(),
        "",
    ]
    width = max(len(n) for n in names)
    lines += ["#define %-*s %s" % (width, n, renamed(n, api)) for n in names]
    lines += ["", "#endif"]
    return "\n".join(lines) + "\n"


def backends_text(names):
    """The three entry points draw.c dispatches to, which are the renames of rEngine's own two."""
    mine = [n for n in names if n.startswith("re_backend_seam_")]
    lines = [
        "/* GENERATED by tools/seam_prefix.py -- do not edit.",
        " *",
        " * backend_seam.c is compiled once per graphics API, each copy calling its own prefixed seam",
        " * (spec 126 decision 3), so its entry points exist three times under three names. This is the",
        " * header draw.c dispatches through -- the whole runtime cost of keeping --renderer a runtime",
        " * switch, paid once per window rather than once per draw.",
        " */",
        "#ifndef RENGINE_SEAM_BACKENDS_H",
        "#define RENGINE_SEAM_BACKENDS_H",
        '#include "render/backend.h"',
        "#include <SDL.h>",
        "",
    ]
    for api in APIS:
        guard = "#ifdef __APPLE__" if api == "metal" else None
        if guard:
            lines.append(guard)
        for name in mine:
            signature = "Uint32 %s(void);" if name.endswith("window_flags") else \
                        "ReBackend *%s(SDL_Window *window, ReFontSet *fonts);"
            lines.append(signature % renamed(name, api))
        if guard:
            lines.append("#endif")
    lines += ["", "#endif"]
    return "\n".join(lines) + "\n"


def outputs():
    names = symbols()
    files = {RENDER / ("seam_prefix_%s.h" % api): header_text(api, names) for api in APIS}
    files[RENDER / "seam_backends.h"] = backends_text(names)
    return names, files


def generate():
    names, files = outputs()
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
    print("seam prefix: %d symbols renamed for %s" % (len(names), ", ".join(APIS)))


def check():
    names, files = outputs()
    problems = []
    for path, text in files.items():
        if not path.exists():
            problems.append("%s is missing; run `python3 tools/seam_prefix.py generate`" % path.relative_to(ROOT))
        elif path.read_text(encoding="utf-8") != text:
            problems.append("%s no longer matches the headers it is generated from; run "
                            "`python3 tools/seam_prefix.py generate`" % path.relative_to(ROOT))
    for problem in problems:
        print("ERROR: %s" % problem)
    if problems:
        return 1
    print("seam prefix: %d symbols renamed per copy, and the generated headers match their sources."
          % len(names))
    return 0


if __name__ == "__main__":
    command = sys.argv[1] if len(sys.argv) > 1 else "check"
    if command == "generate":
        generate()
    elif command == "check":
        sys.exit(check())
    elif command == "symbols":
        for name in symbols():
            print(name)
    else:
        raise SystemExit("usage: seam_prefix.py [generate|check|symbols]")
