#!/usr/bin/env python3
"""Compile the owned Vulkan GLSL shaders to committed SPIR-V arrays (spec 073 decision 6).

generate: run glslc on every source under orchestrator/native/render/shaders and rewrite ui_spv.h.
check:    fail when ui_spv.h is missing or was generated from different sources (hash mismatch).
Standard library only; glslc is needed for generate, never for check or for building the desktop.
"""
import hashlib
import pathlib
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHADERS = ROOT / "orchestrator" / "native" / "render" / "shaders"
HEADER = SHADERS / "ui_spv.h"
SOURCES = [("ui.vert", "re_ui_vert_spv"), ("ui.frag", "re_ui_frag_spv")]
TARGET = "vulkan1.3"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def generate():
    glslc = shutil.which("glslc")
    if not glslc:
        sys.exit("glslc not found; install the Vulkan SDK or Homebrew shaderc")
    version = subprocess.run([glslc, "--version"], check=True, capture_output=True, text=True).stdout.strip().splitlines()[0]
    parts = ["/* Generated by tools/shaders.py from the GLSL sources next to this file; do not edit.",
             " * Regenerate with `python3 tools/shaders.py generate`; `check` verifies the source hashes below.",
             " * Compiler: %s, target %s. */" % (version, TARGET),
             "#ifndef RENGINE_UI_SPV_H", "#define RENGINE_UI_SPV_H", "#include <stdint.h>"]
    with tempfile.TemporaryDirectory() as tmp:
        for name, symbol in SOURCES:
            source = SHADERS / name
            out = pathlib.Path(tmp) / (name + ".spv")
            subprocess.run([glslc, "--target-env=" + TARGET, "-O", "-o", str(out), str(source)], check=True)
            data = out.read_bytes()
            if len(data) % 4:
                sys.exit("%s: SPIR-V size is not a multiple of four" % name)
            words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
            parts.append("#define %s_SOURCE_SHA256 \"%s\"" % (symbol.upper(), digest(source)))
            parts.append("static const uint32_t %s[%d] = {" % (symbol, len(words)))
            for i in range(0, len(words), 8):
                parts.append("  " + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",")
            parts.append("};")
    parts.append("#endif")
    HEADER.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print("wrote %s (%s)" % (HEADER.relative_to(ROOT), version))


def check():
    if not HEADER.exists():
        sys.exit("%s is missing; run `python3 tools/shaders.py generate`" % HEADER.relative_to(ROOT))
    text = HEADER.read_text(encoding="utf-8")
    problems = []
    for name, symbol in SOURCES:
        expected = "#define %s_SOURCE_SHA256 \"%s\"" % (symbol.upper(), digest(SHADERS / name))
        if expected not in text:
            problems.append("%s changed since ui_spv.h was generated" % name)
        if ("static const uint32_t %s[" % symbol) not in text:
            problems.append("%s is not defined in ui_spv.h" % symbol)
    if problems:
        sys.exit("\n".join(problems) + "\nRun `python3 tools/shaders.py generate` and commit the result.")
    print("Vulkan shaders: ui_spv.h matches %d GLSL sources." % len(SOURCES))


if __name__ == "__main__":
    command = sys.argv[1] if len(sys.argv) > 1 else "check"
    if command == "generate":
        generate()
    elif command == "check":
        check()
    else:
        sys.exit("usage: tools/shaders.py generate|check")
